 --PREVENCIÓN DE RIESGOS LABORALES DE LA POLICIA NACIONAL.
insert into guias (id, nombre_guia, tipo_inspeccion, orden, fecha_alta, username_alta) values 
(SEQ_GUIAS.NEXTVAL, 'PRL (Policía Nacional)', 'I.T_PRL', 15,trunc(sysdate), 'system');

insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación documentada de las actividades preventivas encuadradas en las especialidades contempladas no asumidas por el Servicio de Prevención y para cuya utilización se ha recurrido a un Servicio de Prevención Ajeno.', 0);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Estructura, Dependencia y Ámbito de Competencia. Analizar la estructura y configuración actual del SP.', 1);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar el concierto suscrito con el Servicio de Prevención de riesgos Laborales ajeno, al objeto de comprobar si reúne las condiciones dispuestas en el artículo 20 apartado 1 del R.D. 39/1997.', 2);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Analizar la situación competencial en materia de vigilancia de la salud.', 3);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Personal destinado en el Servicio de Prevención con indicación de las titulaciones en materia de prevención tanto en la estructura central como territorial, así como personal de apoyo y auxiliar.', 4);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Recursos Humanos. Examinar la norma en la que se materializa la creación del S.P.', 5);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar el catálogo de recursos humanos destinados en S.P.', 6);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar el personal destinado realmente en S.P concretando situación: fijos, en comisión de servicio, adscripción temporal, etc.', 7);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar la documentación, si existe, en la que conste la creación de dichos puestos de trabajo, sus funciones y tipo de dependencia (orgánica y funcional) ', 8);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar ajuste entre lo dispuesto en el Plan de Prevención y la situación real.', 9);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Medios materiales de que dispone para desarrollar la acción preventiva encomendada y asumida. Acreditar si los Técnicos del Servicio de Prevención están instruidos en el uso de los equipos y si éstos están, en su caso, calibrados.', 10);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar copia documental por muestreo de las últimas calibraciones de aquel instrumental que lo requiere y si se encuentra en vigor.', 11);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Medios Materiales . Verificar si los técnicos poseen el conocimiento necesario sobre el manejo de los instrumentos.', 12);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Medios Materiales . Verificar si son suficientes. ', 13);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Fecha de aprobación del Plan y Manual de Prevención de Riesgos Laborales y modificaciones que se hayan llevado a cabo, en su caso, en cada uno de los documentos.', 14);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Deficiencias e incumplimientos detectados y puestos de manifiesto durante el desarrollo e implantación del Plan.', 15);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'En el caso de haberse detectado deficiencias, ¿se han elevado propuestas de revisión y modificación del Plan de Prevención al objeto de adaptarlo a la situación real que permita llevar a cabo adecuadamente las actividades preventivas de las especialidades asumidas por el Servicio? En caso afirmativo acreditar las propuestas.', 16);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar cumplimiento de lo establecido en el Art. 3 del RD 67/2010 (Plan de Prevención).', 17);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar si se ha realizado o se está realizando alguna revisión del Plan a fecha de hoy: contenido y alcance.', 18);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de Evaluaciones de Riesgo realizadas en el periodo indicado con especificación de si son iniciales o reevaluaciones (por reformas estructurales, nuevos equipos de trabajo, haber transcurrido cuatro años y aquellas otras circunstancias que exijan una revisión y actualización).', 19);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de plantillas o unidades a las que se ha practicado revisiones de evaluación indicando las circunstancias y el Servicio de Prevención que las ha llevado a cabo. Previsiones o programación de las evaluaciones pendientes de realizar y el Servicio de Prevención que vaya a asumir su realización.', 20);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar quién realiza las Evaluaciones de Riesgo Servicio Prevención Propio, Servicio Prevención Ajeno o una fórmula intermedia. ', 21);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Si se ha recurrido a un SPA (total o parcialmente) verificar todos aquellos aspectos relativos a la realización de dichas Evaluaciones: distribución geográfica y temporal (cronograma), si se realizan por separado o conjuntamente, que tipo de riesgos evalúa uno y otro servicio de prevención, etc.', 22);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Evaluaciones de Riesgos. Verificar el grado de cumplimiento de los distintos aspectos exigidos en la normativa de aplicación.', 23);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Propuesta de Planificación Preventiva. Actividades de seguimiento y control de las Fichas de Seguimiento de las Acciones Correctoras.', 24);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Control del cumplimiento de la Actividad Preventiva: que forma o de que instrumento dispone para velar porque la misma sea eficaz e incluso vigilar y supervisar que las distintas unidades policiales llevan a cabo estas actividades conforme a la citada normativa.', 25);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar si el SP controla adecuadamente el cumplimiento de la IOPR 006 y el procedimiento de seguimiento y control de las medidas correctoras por parte de las distintas Unidades.', 26);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Planes de Emergencia/Autoprotección supervisados y/o elaborados por el Servicio de Prevención durante el periodo.', 27);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Planes de Emergencia y de Autoprotección. Indicar simulacros realizados.', 28);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Análisis de las actas levantadas con ocasión de la realización de simulacros.', 29);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar si el modelo de Plan de Medidas de Emergencia se ha distribuido entre las plantillas, así como que actividades de supervisión y asesoramiento han desarrollado al respecto.', 30);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar el mecanismo de control de plantillas que contestan, de la supervisión y asesoramiento que se ha ejercido, igual respecto de los simulacros, etc.', 31);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Protocolos de reconocimiento médico específico en relación a los riesgos en el puesto de trabajo enumerando aquellos que por razón de la naturaleza de la actividad profesional sean de carácter obligatorio, con indicación de la periodicidad establecida.', 32);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Informes, dictámenes y recomendaciones emitidos en materia de vigilancia de la salud: de aptitud física, de aptitud para el trabajo, de cambio de puesto de trabajo por motivos de salud, sobre riesgo durante el embarazo, parto reciente o lactancia o cualquier circunstancia o situación en el ámbito de la evaluación de la salud de los empleados públicos en relación con las condiciones del puesto de trabajo.', 33);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Actividades en materia de asistencia sanitaria, prevención y promoción de la salud dentro de las previsiones que, en materia de seguridad y salud laboral, tiene establecidos el Servicio de Prevención.', 34);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación y organización del personal sanitario capacitado en la materia tanto a nivel central como territorial.', 35);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Recursos materiales: relación de instalaciones, medios materiales sanitarios y de archivo de los que está dotado el servicio de prevención para desarrollar las actividades sanitarias asignadas.', 36);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Procedimientos de actuación y mecanismos de coordinación entre el Servicio Sanitario y el Servicio de Prevención en materia de vigilancia y control de la salud de los empleados públicos en el ámbito de la Dirección General de la Policía.', 37);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar si se han definido los protocolos específicos para llevar a cabo la vigilancia de la salud en función de los riesgos a los que están sometidos los funcionarios.', 38);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Examinar el Manual de Vigilancia de la Salud donde están definidos los protocolos aplicables, en caso de que el párrafo anterior sea positivo.', 39);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar si se realizan controles del estado de salud de los trabajadores en orden a la prevención de los riesgos inherentes al trabajo.', 40);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Vigilancia de la Salud. En caso afirmativo, comprobar si la vigilancia de la salud es realizada por personal acreditado y cualificado, indicando los responsables de esta actividad.', 41);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Recabar información respecto a la asunción de competencias en relación con la vigilancia de la salud.', 42);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relacionar con el punto primero y en particular, clarificar los aspectos por los que no ejerce esta competencia que tiene atribuida por normativa. Caso de no realizar dicho cometido, conocer si se han analizado las causas y en su caso, actuaciones que se hayan adoptado o emprendido para dar a conocer dicha situación a la superioridad, al objeto de adoptar las medidas correspondientes. De ser así, conocer el estado en que se encuentra.', 43);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Analizar la situación actual respecto de la asunción de funciones en materia de primeros auxilios y gestión de botiquines.', 44);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar cumplimiento art.25 (personal sensible) y 26 (embarazo). En especial determinar cumplimiento IOPR 008 de medidas para promover la mejora de la seguridad y salud de la funcionaria embarazada.', 45);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de accidentes de trabajo con indicación de mortales, graves y que afecten a más de cuatro leves.', 46);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de aquellos incidentes contemplados en el documento “Criterio unificado sobre la valoración de la gravedad de los accidentes e incidentes en las Fuerzas y Cuerpos de Seguridad del Estado, a efectos de notificación e investigación.', 47);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de comunicaciones efectuadas a la Inspección de Trabajo de conformidad con lo establecido en la disposición adicional cuarta del RD 67/2010.', 48);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar cumplimientos procedimientos 1300 y 1301, control estadístico de la siniestralidad y relación de accidentes y enfermedades profesionales. Definir las causas que lo obstaculizan o impiden y soluciones o alternativas existentes para su solución, en el caso de incumplimiento.', 49);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Fichas de información de carácter general, especifico o de cualquier otra naturaleza elaborados por el Servicio de Prevención, así como Manuales, Campañas de Prevención, Trípticos y cualquier otro medio informativo. Procedimiento empleado para justificar la recepción por el personal.', 50);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar las medidas adoptadas para que los empleados públicos reciban información sobre los riesgos y las medidas de prevención y protección que afecten a las dependencias policiales, a su actividad o función específica y las medidas de emergencia: examinar manuales, boletines informativos, evaluaciones de riesgos, documentos acreditativos firmados por el trabajador, página Web, etc. ', 51);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Existencia de cauces o procedimientos de información como vehículo de transmisión de instrucciones en materia preventiva: examinar modelos de actas, instrucciones u órdenes de trabajo con acuse de recibo, etc.', 52);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relacionar las actividades formativas desplegadas en materia preventiva por ese Servicio de Prevención, así como aquellas otras realizadas en colaboración con otros órganos, unidades o servicios.', 53);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Cursos, conferencias y otras actividades formativas recibidas por el personal del Servicio de Prevención.', 54);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Formación impartida y recibida. De cada una de las actividades contempladas en los puntos anteriores se realizará una breve descripción que al menos contenga:
Materia de Prevención de Riesgos laborales tratada: General, específica, Medidas de Emergencia…
Personal que la impartió.Personal que lo recibió.Número de alumnos.
Duración.
Método utilizado: Telemático, presencial, divulgativo,…', 55);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar los planes de formación o la aportación del servicio de prevención en los distintos planes formativos: ingreso, promoción y especialización; introducción de cambios en los equipos de trabajo o nuevas tecnologías,Delegados de Prevención,  mandos con responsabilidades en la gestión de la prevención, etc.', 56);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar la formación recibida por los componentes del Servicio de Prevención, en materia preventiva, comprobando registros sobre características de los cursos  e instituciones que los imparten.', 57);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Breve descripción de las actividades de asesoramiento y de informes o dictámenes emitidos por el Servicio de Prevención relacionados con el sistema de gestión de la prevención de riesgos laborales en el ámbito de la Dirección General de la Policía.', 58);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Verificar actuaciones, estudios e informes realizados en relación con las funciones encomendadas al Servicio de Prevención  (Art. 18 del RD 2/2006 y 31 de la Ley de PRL.)', 59);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Qué tipo de medidas se han adoptado para que las distintas plantillas y unidades del Cuerpo Nacional de Policía dispongan de la información y las instrucciones adecuadas a seguir en materia de coordinación de actividades empresariales.', 60);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, '¿Se informa al Servicio de Prevención de los contratos de prestación de obras o servicios suscritos en el ámbito de la actividad de la Dirección General de la Policía? En caso afirmativo indicar número y tipo de actividad contratada.', 61);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Número y tipo de actuaciones en esta materia solicitadas al Servicio de Prevención por los titulares de los órganos de la Institución.', 62);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Explicar brevemente si existe o se ejerce por el Servicio de Prevención algún tipo de control, vigilancia o seguimiento sobre las medidas previstas para la coordinación de actividades empresariales.', 63);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar la relación de órganos policiales a los que para su conocimiento y difusión se ha enviado el procedimiento 404 de Coordinación de Actividades Empresariales.', 64);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Ver informaciones suministradas o actuaciones realizadas en esta materia por el Servicio de Prevención con otros organismos o empresas en aquellas actividades concurrentes en los que hayan tenido participación.', 65);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar si se ha informado a los empleados públicos la existencia de riesgos derivado de la concurrencia de actividades empresariales.', 66);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'En referencia a lo dispuesto en el Art. 23 de la Ley de Prevención de Riesgos Laborales, relación detallada de la documentación correspondiente a la actividad desplegada en el ámbito de la Dirección General de la Policía en materia de prevención de riesgos laborales, que se encuentra bajo la custodia y archivo de ese Servicio de Prevención.', 67);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar por muestreo el archivo y los registros documentales reglamentarios en materia preventiva: Evaluaciones de Riesgos, notificación e investigación de accidentes, etc.', 68);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de Procedimientos e Instrucciones Operativas aprobados, pendientes de aprobación o en fase de elaboración y estudio.', 69);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'En su caso, informando sobre su causa o justificación, relación de Procedimientos o de Instrucciones Operativas en vigor que estén o hayan sido objeto de actualización o revisión.', 70);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Conocer y valorar la actividad en relación con los procedimientos implantados, así como los que se encuentren pendientes de aprobación o redacción y el tiempo empleado en su elaboración.', 71);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Informar brevemente, en su caso, sobre los siguientes aspectos:
Registros de Actuaciones por Acoso Laboral. 
Relación de Acuerdos adoptados por Acoso laboral.  
Número de Informes elaborados sobre situación previa de los riesgos psicosociales en la Unidad afectada.
Relación de las actuaciones de seguimiento respecto del cumplimiento de las medidas preventivas/correctoras propuestas en el marco de los riesgos laborales.
Número de denuncias falsas.', 72);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Comprobar las actuaciones desarrolladas  y  las obligaciones impuestas al Servicio de Prevención al amparo de lo establecido en el mencionado  Protocolo.', 73);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Relación de propuestas de mejora y sugerencias en materia de prevención recibidas en el Servicio de Prevención. Examinar su número, proyección, adecuación y coherencia con la normativa vigente.', 74);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Las actividades preventivas se documentan a través de una programación y memoria anual.', 75);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Elaboración de la Memoria Anual. Indicar si se contienen las prioridades fijadas y los objetivos alcanzados o en fase de elaboración a este respecto.', 76);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Elaboración de la Memoria Anual. Informe de Auditoría Interna realizado por ese Servicio de Prevención.', 77);
insert into guia_Pasos (id, id_guia, paso, orden) values (SEQ_PASOSGUIA.NEXTVAL, SEQ_GUIAS.CURRVAL, 'Analizar la  actividad desplegada por la Subdirección General de Recursos Humanos en materia de prevención de riesgos laborales a través del Servicio  de Prevención, en unión de las conclusiones y valoraciones alcanzadas sobre su situación.', 78);
