BEGIN
  FOR cur_rec IN (SELECT object_name, object_type 
                  FROM   user_objects
                  WHERE  object_type IN ('TABLE', 'SEQUENCE')) LOOP
    BEGIN
      IF cur_rec.object_type = 'TABLE' THEN
        EXECUTE IMMEDIATE 'DROP ' || cur_rec.object_type || ' "' || cur_rec.object_name || '" CASCADE CONSTRAINTS';
      ELSE
        EXECUTE IMMEDIATE 'DROP ' || cur_rec.object_type || ' "' || cur_rec.object_name || '"';
      END IF;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.put_line('FAILED: DROP ' || cur_rec.object_type || ' "' || cur_rec.object_name || '"');
    END;
  END LOOP;
END;
/

DROP PUBLIC SYNONYM PARAMETROS;
DROP PUBLIC SYNONYM CLASE_USUARIO;
DROP PUBLIC SYNONYM CUERPOSESTADO;
DROP PUBLIC SYNONYM DEPARTAMENTO;
DROP PUBLIC SYNONYM EMPLEO;
DROP PUBLIC SYNONYM PUESTOSTRABAJO;
DROP PUBLIC SYNONYM PROVINCIAS;
DROP PUBLIC SYNONYM MUNICIPIOS;
DROP PUBLIC SYNONYM ALERTAS;
DROP PUBLIC SYNONYM NOTIFICACIONES;
DROP PUBLIC SYNONYM ALERTAS_NOTIFICACIONES_USUARIO;
DROP PUBLIC SYNONYM REG_ACTIVIDAD;
DROP PUBLIC SYNONYM SUGERENCIA;
DROP PUBLIC SYNONYM TIPOS_UNIDAD;
DROP PUBLIC SYNONYM TIPODOCUMENTACIONPREVIA;
DROP PUBLIC SYNONYM DOCUMENTACION_PREVIA;
DROP PUBLIC SYNONYM TIPO_DOCUMENTO;
DROP PUBLIC SYNONYM TIPO_EQUIPO;
DROP PUBLIC SYNONYM USERS;
DROP PUBLIC SYNONYM EQUIPO;
DROP PUBLIC SYNONYM MIEMBROS;
DROP PUBLIC SYNONYM TIPOS_INSPECCION;
DROP PUBLIC SYNONYM INSPECCIONES;
DROP PUBLIC SYNONYM INSPECCIONES_ASOCIADAS;
DROP PUBLIC SYNONYM DOCUMENTOS_BLOB;
DROP PUBLIC SYNONYM DOCUMENTOS;
DROP PUBLIC SYNONYM DOCUMENTOS_INSPECCION;
DROP PUBLIC SYNONYM CONFIG_RESPUESTAS_CUESTIONARIO;
DROP PUBLIC SYNONYM MODELOSCUESTIONARIOS;
DROP PUBLIC SYNONYM AREASCUESTIONARIO;
DROP PUBLIC SYNONYM PREGUNTASCUESTIONARIO;
DROP PUBLIC SYNONYM CUESTIONARIO_PERSONALIZADO;
DROP PUBLIC SYNONYM CUEST_PER_PREGUNTAS;
DROP PUBLIC SYNONYM CUESTIONARIOS_ENVIADOS;
DROP PUBLIC SYNONYM RESPUESTASCUESTIONARIO;
DROP PUBLIC SYNONYM RESPUESTAS_CUEST_DOCS;
DROP PUBLIC SYNONYM RESPUESTA_DATOS_TABLA;
DROP PUBLIC SYNONYM AREAS_USUARIO_CUESTENV;
DROP PUBLIC SYNONYM CUEST_ENV_PLANTILLA;
DROP PUBLIC SYNONYM SOLICITUD_DOC_PREVIA;
DROP PUBLIC SYNONYM SOLICITUD_PREVIA_DOCS;
DROP PUBLIC SYNONYM GUIAS;
DROP PUBLIC SYNONYM GUIA_PASOS;
DROP PUBLIC SYNONYM GUIA_PERSONALIZADA;
DROP PUBLIC SYNONYM GUIA_PERSONALIZADA_PASOS;
DROP PUBLIC SYNONYM GUIA_INSPECCION;
DROP PUBLIC SYNONYM MODELOS_INFORME;
DROP PUBLIC SYNONYM AREAS_INFORME;
DROP PUBLIC SYNONYM SUBAREAS_INFORME;
DROP PUBLIC SYNONYM MODELOS_INFORME_PERSONALIZADOS;
DROP PUBLIC SYNONYM INFORME_PERSONAL_SUBAREAS;
DROP PUBLIC SYNONYM INFORMES;
DROP PUBLIC SYNONYM RESPUESTAS_INFORME;
DROP PUBLIC SYNONYM ASIGN_SUBAREA_INFORME_USER;

DROP PUBLIC SYNONYM SEQ_ALERTA;
DROP PUBLIC SYNONYM SEQ_AREASCUESTIONARIOS;
DROP PUBLIC SYNONYM SEQ_AREASINFORME;
DROP PUBLIC SYNONYM SEQ_CLASE;
DROP PUBLIC SYNONYM SEQ_CUERPOS;
DROP PUBLIC SYNONYM SEQ_CUESTIONARIOPERSONALIZADO;
DROP PUBLIC SYNONYM SEQ_CUESTIONARIOSENVIADOS;
DROP PUBLIC SYNONYM SEQ_DEPARTAMENTO;
DROP PUBLIC SYNONYM SEQ_DOCUMENTACION_PREVIA;
DROP PUBLIC SYNONYM SEQ_DOCUMENTOS;
DROP PUBLIC SYNONYM SEQ_DOCUMENTOSBLOB;
DROP PUBLIC SYNONYM SEQ_EMPLEO;
DROP PUBLIC SYNONYM SEQ_EQUIPO;
DROP PUBLIC SYNONYM SEQ_GUIAPERSONALIZADA;
DROP PUBLIC SYNONYM SEQ_GUIAS;
DROP PUBLIC SYNONYM SEQ_INFORME;
DROP PUBLIC SYNONYM SEQ_INFORMEPERSONAL;
DROP PUBLIC SYNONYM SEQ_INSPECCION;
DROP PUBLIC SYNONYM SEQ_MIEMBROS;
DROP PUBLIC SYNONYM SEQ_MODELOINFORME;
DROP PUBLIC SYNONYM SEQ_MODELOSCUESTIONARIOS;
DROP PUBLIC SYNONYM SEQ_MUNICIPIO;
DROP PUBLIC SYNONYM SEQ_NOTIFICACIONES;
DROP PUBLIC SYNONYM SEQ_PASOSGUIA;
DROP PUBLIC SYNONYM SEQ_PREGUNTASCUESTIONARIO;
DROP PUBLIC SYNONYM SEQ_PUESTO_TRABAJO;
DROP PUBLIC SYNONYM SEQ_REGISTRO;
DROP PUBLIC SYNONYM SEQ_RESPUESTATABLA;
DROP PUBLIC SYNONYM SEQ_SOLDOCPREVIA;
DROP PUBLIC SYNONYM SEQ_SUBAREASINFORME;
DROP PUBLIC SYNONYM SEQ_SUGERENCIAS;
DROP PUBLIC SYNONYM SEQ_TIPO_EQUIPO;
DROP PUBLIC SYNONYM SEQ_TIPODOCUMENTACIONPREVIA;    
COMMIT;

