insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(1, 'Policía Nacional', 'PN','system', current_date, null, null,null,null);
insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(2, 'Guardia Civil','GC', 'system', current_date, null, null,null,null);
insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(3, 'Cuerpo General de la Administración','CGA', 'system', current_date, null, null,null,null);
insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(4, 'Cuerpos Comunes de la Defensa','CCD','system', current_date, null, null,null,null);
insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(5, 'Contratados','CONTR', 'system', current_date, null, null,null,null);
insert into CUERPOSESTADO (id, descripcion, nombre_corto,username_alta, fecha_alta, username_modif, fecha_modif, username_baja, fecha_baja) values(6, 'Correos y Telégrafos','CT', 'system', current_date, null, null,null,null);
 
 
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Subdirector General', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Secretario Técnico', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Jefe de Servicios de Inspección', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Responsable Estudios y Programas', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Jefe de Equipo Inspecciones', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Inspector-Auditor', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Jefe de Apoyo', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Jefe de Sección', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Personal de Apoyo', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Jefe de Negociado', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Fuera de Catálogo (Conductores)', Sysdate, 'system');
insert into PUESTOSTRABAJO (id,descripcion, fecha_alta, username_alta) values(SEQ_PUESTO_TRABAJO.nextval, 'Secretaria de N30', Sysdate, 'system');
 
 
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'IAPRL', 'Inspecciones Área Prevención de Riesgos Laborales');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'IG', 'Inspecciones Generales');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'IS', 'Inspecciones de Seguimiento');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'II', 'Inspecciones Incidentales');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'IPRL', 'Inspecciones Prevención de Riesgos Laborales');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'CIES', 'Inspecciones Temáticas (CIES).');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'SCQ', 'Servicio de Calidad y Quejas');
insert into TIPO_EQUIPO (ID, CODIGO, DESCRIPCION) Values (seq_tipo_equipo.nextval, 'SO', 'Secretaria Y Otros');

  ------------- tipos documentacion previa

Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Comisiones Provinciales de Seguridad Privada de los años 2014 y 2015', 'ACPSP', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Comisiones Provinciales de Seguridad Privada de los años 2014 y 2015', 'ACPSP', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Comisiones de Coordinación de Policía Judicial de los años 2014 y 2015', 'ACCPJ', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Comisiones de Coordinación de Policía Judicial de los años 2014 y 2015', 'ACCPJ', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Juntas Locales de Seguridad de los años 2014 y 2015', 'AJLS', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Juntas Locales de Seguridad de los años 2014 y 2015', 'AJLS', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Actas de las Juntas de Coordinación de 2015', 'AJC', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Catálogo de Puestos de Trabajo (última aprobación CECIR) y fuerza en revista', 'CPT', 'XLS, XLSX', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Convenios de colaboración con Policías Locales (tanto genéricos como específicos)', 'CCPL', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Convenios de colaboración con Policías Locales (tanto genéricos como específicos)', 'CCPL', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Copia de las actas de las reuniones sindicales celebradas en 2014 y 2015', 'CAS', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Documentación relativa al Plan Territorial. Objetivos operativos fijados para 2015', 'PTyO', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Evaluación de Riesgos Laborales', 'PRL', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Libro de Organización y Libro de Normas de Régimen Interno', 'LOYRI', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Mapa con la distribución territorial de sus Unidades subordinadas.', 'mapa', 'JPG, JPEG, PNG, BMP', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Memoria Anual de 2015', 'MA', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Memoria Anual de 2015', 'MA', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Organigrama de la Comandancia (Unidades Territoriales y Especialidades)', 'organigrama', 'DOC, DOCX, PPTX, PPT, PUB', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Organigrama de la Compañía (Unidades Territoriales y Especialidades)', 'organigrama', 'DOC, DOCX, PPTX, PPT, PUB', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Organigrama de la Zona (Unidades Territoriales y Especialidades)', 'organigrama', 'DOC, DOCX, PPTX, PPT, PUB', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Organigramas de la Unidad, con detalle de sus Unidades y Servicios', 'organigrama', 'DOC, DOCX, PPTX, PPT, PUB', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Plan anual de la Unidad Orgánica de Policía Judicial vigente', 'PAUOPJ', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Plan de Emergencia', 'PE', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Plan de Emergencia', 'PE', 'PDF', 'PN');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Plan de Seguridad Ciudadana', 'PSC', 'PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Relación de mandos de las distintas Unidades, de categoría Oficial, con indicación de teléfonos y correos electrónicos de contacto', 'RM', 'DOC, DOCX, PDF', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Relación de municipios que configuran la demarcación de la compañía', 'RMD', 'DOC, DOCX', 'GC');
Insert into  tipodocumentacionprevia (ID,DESCRIPCION,NOMBRE,EXTENSIONES,AMBITO) Values (seq_tipodocumentacionprevia.nextval, 'Relación del Equipo Directivo con indicación del nombre y apellidos, categoría y cargo, números de teléfono y dirección de correo electrónico', 'RM', 'DOC, DOCX', 'PN');

 

--Respuestas básicas

Insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('TEXTAREA', '1', '1');
Insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('INPUT', '1', '1');
Insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('ADJUNTOINPUT', '1', '1');
Insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('ADJUNTORADIOSINO', '1', '1');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('RADIOSINO', 'SI', 'Sí');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('RADIOSINO', 'NO', 'No');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('RADIOCALIDAD', 'BUENO', 'Bueno');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('RADIOCALIDAD', 'ACEPTABLE', 'Aceptable');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (seccion,clave,valor) values ('RADIOCALIDAD', 'DEFICIENTE', 'Deficiente');

insert into tipos_inspeccion (codigo,descripcion) values ('I.G.P.','I.Gral.Periodica');
insert into tipos_inspeccion (codigo,descripcion) values ('I.G.S.','I.Gral.Seguimiento');
insert into tipos_inspeccion (codigo,descripcion) values ('I.T_PRL','I.Temática PRL');
insert into tipos_inspeccion (codigo,descripcion) values ('I.T_CIE','I.Temática CIE');
insert into tipos_inspeccion (codigo,descripcion) values ('I.T_OT','I.Temática otros');
insert into tipos_inspeccion (codigo,descripcion) values ('I.E_INCD','I. Incidental extraordinaria');
insert into tipos_inspeccion (codigo,descripcion) values ('I.E_PRL','I.PRL extraordinaria');
insert into tipos_inspeccion (codigo,descripcion) values ('I.E_PUNT','I.Puntual extraordinaria');

INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.host','smtp.gmail.com');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.ssl.trust','smtp.gmail.com');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.port','587');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.user','progesinipss@gmail.com');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','UserPwd','ipss2016');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.auth','true');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('mail','mail.smtp.starttls.enable','true');

INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('datosApoyo','ApoyoCorreo','mmayo@interior.es');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('datosApoyo','ApoyoNombre','Manuel Mayo Rodríguez');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('datosApoyo','ApoyoPuesto','Inspector Auditor, Jefe del Servicio de Apoyo');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('datosApoyo','ApoyoTelefono','91.537.25.41');

INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','DOC','application/msword');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','DOCX','application/vnd.openxmlformats-officedocument.wordprocessingml.document');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','PPT','application/vnd.ms-powerpoint');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','PPTX','application/vnd.openxmlformats-officedocument.presentationml.presentation');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','XLS','application/vnd.ms-excel');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','XLSX','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','JPEG','image/jpeg');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','PNG','image/png');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','BMP','image/bmp');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','PUB','application/x-mspublisher');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('extensiones','PDF','application/pdf');

INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('URLPROGESIN','PN', 'http://194.224.253.45:8080/progesin');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('URLPROGESIN','GC', 'http://194.224.253.45:8080/progesin');
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('URLPROGESIN','OTROS', 'http://194.224.253.45:8080/progesin');

-- EN PRODUCCIÓN ELIMINAR ezentis.com COMO DOMINIO PERMITIDO
INSERT INTO PARAMETROS(seccion, clave, valor) VALUES ('dominiosCorreo','dominiosCorreo', 'ezentis.com|interior.es|policia.es|dgp.mir.es|guardiacivil.org|guardiacivil.es');

-- textos vista solicitud según ámbito
-- insert into parametros(seccion, clave, valor) values ('vistaSolicitudGC', 'bloque1', 'Lorem Ipsum');
-- insert into parametros(seccion, clave, valor) values ('vistaSolicitudPN', 'bloque1', 'Lorem Ipsum');
-- insert into parametros(seccion, clave, valor) values ('vistaSolicitudOTROS', 'bloque1', 'Lorem Ipsum');

--Parametros tareas
Insert into PARAMETROS (CLAVE,SECCION,VALOR) values ('plazoDiasDocumentacion','tareas','5');
Insert into PARAMETROS (CLAVE,SECCION,VALOR) values ('plazoDiasCuestionario','tareas','5');
Insert into PARAMETROS (CLAVE,SECCION,VALOR) values ('correoApoyo','tareas','apoyo_ipss@interior.es');


insert into equipo(id, fecha_alta, jefe_equipo, nombre_equipo, nombre_jefe, id_tipo_equipo, username_alta) values (seq_equipo.nextval, sysdate, 'silpe', 'Equipo A', 'Silvia apellido1 apellido2', 1, 'silpe');
insert into equipo(id, fecha_alta, jefe_equipo, nombre_equipo, nombre_jefe, id_tipo_equipo, username_alta) values (seq_equipo.nextval, sysdate, 'cgonzalez', 'Equipo B', 'CARLOS GONZÁLEZ CASTILLO', 2, 'silpe');
insert into equipo(id, fecha_alta, jefe_equipo, nombre_equipo, nombre_jefe, id_tipo_equipo, username_alta) values (seq_equipo.nextval, sysdate, 'mfgonzalez', 'Equipo C', 'MARCELO FRANCISCO GONZALEZ FERNANDEZ', 3, 'silpe');

insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 1, 'Silvia apellido1 apellido2', 'JEFE_EQUIPO', 'silpe');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 1, 'PEDRO  CARRETERO LIAU', 'MIEMBRO', 'pedro');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 1, 'JOSE MANUEL SIERRA EXOJO', 'MIEMBRO', 'jmanuel');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 1, 'ANTONIO LOPEZ BETRIAN', 'MIEMBRO', 'alopez');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 2, 'CARLOS GONZÁLEZ CASTILLO', 'JEFE_EQUIPO', 'cgonzalez');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 2, 'AMADEO MATEOS CHICO', 'MIEMBRO', 'amateos');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 2, 'ELIAS MARTINEZ ALLER','MIEMBRO','emartinez');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 3, 'MARCELO FRANCISCO GONZALEZ FERNANDEZ', 'JEFE_EQUIPO', 'mfgonzalez');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 3, 'JOSE LUIS CALONGE DELSO', 'MIEMBRO', 'jlcalonge');
insert into miembros(id, id_equipo, nombre_completo, posicion, username) values (seq_miembros.nextval, 3, 'JOSE IGNACIO CEREZO HERNANDEZ', 'MIEMBRO', 'jicerezo');



Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Subdirección General de Inspección y Servicios', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Secretaría Técnica', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Jefatura de Inspecciones', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Equipos de Inspecciones Generales', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Equipo de Inspecciones Temáticas y PRL', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Gabinete de Estudios y Análisis', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Servicio de Calidad y Quejas', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Servicio de Apoyo', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Secretaría', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Asesores', Sysdate, 'system');
Insert into DEPARTAMENTO (ID,DESCRIPCION, fecha_alta, username_alta) values (SEQ_DEPARTAMENTO.nextval,'Conductores', Sysdate, 'system');

insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Teniente General','Tte. Gral.' );
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'General de División','Gral. Div.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'General de Brigada','Gral. Bri.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Coronel','Col.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Teniente Coronel','TCol.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Comandante','Comte.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Capitán','Ctan.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Teniente','Tte.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Alférez','Alfz.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Suboficial Mayor','Subof. May.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Subteniente','Subte.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Brigada','Bgda.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Sargento Primero','Sgto.1');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Sargento','Sgto.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Cabo Mayor','Cab.1');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Cabo','Cab.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,2, 'Guardia Civil','Gua.Civ.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Comisario Principal','Com. Pral');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Comisario','Com.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Inspector Jefe','Insp.J.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Inspector','Insp.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Facultativo','Facul.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Subinspector','Subins.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Oficial de Policía','Ofi.Pol.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,1, 'Policía','Pol.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'General de Brigada','Gral. Brig.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Coronel','Col.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Teniente Coronel','TCol.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Comandante','Comte.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Capitán','Ctan.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Teniente','Tte.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,4, 'Alférez','Alf.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Técnico de la Administración Central','TecAdmCent.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Técnico Superior de Sistemas','TecSupSis.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Facultativo','Facul.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Secretaría','Secre.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Administrativo','Adminis.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,3, 'Auxiliar Administrativo','AuxAdminis.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,5, 'Técnico','Tec.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,5, 'Administrativo','Adminis.');
insert into EMPLEO (id,ID_CUERPO,descripcion,NOMBRE_CORTO) values(SEQ_EMPLEO.nextval,6, 'Ejecutivo Post. Y de Telecomunicaciones','CEPyT.');

insert into clase_usuario(id_clase,clase) values (seq_clase.nextval,'FCSE');
insert into clase_usuario(id_clase,clase) values (seq_clase.nextval,'FCSE-FC');
insert into clase_usuario(id_clase,clase) values (seq_clase.nextval,'RPT');
insert into clase_usuario(id_clase,clase) values (seq_clase.nextval,'RPT-FC');

Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('acabrero','CABRERO','GARCIA','correo@guardiacivil.es','n16716','A1',null,'ACTIVO',to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 04:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','ANDRES','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_ADMIN','665566544',null,null,'user_alta',null,null,'2','8','17','6','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('system','system','system','correo@guardiacivil.es','111111111','A1',null,'ACTIVO',to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'20','System','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_ADMIN','665566544',null,null,'user_alta',null,null,'2','8','17','1','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('ajgarcia','GARCIA','ABASCAL','correo@guardiacivil.es','n24519','A1',null,'ACTIVO',to_timestamp('01/02/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/06/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','ANGEL JESUS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','3','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('alopez','LOPEZ','BETRIAN','correo@guardiacivil.es','n10971','A1',null,'ACTIVO',to_timestamp('12/11/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/04/20 14:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'15','ANTONIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'3','8','36','5','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('alopezc','LOPEZ','CONTRERAS','correo@guardiacivil.es','n22162','A1',null,'ACTIVO',to_timestamp('01/04/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','ANTONIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'4','8','36','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('amateos','MATEOS','CHICO','correo@guardiacivil.es','n17702','A1',null,'ACTIVO',to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 05:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','AMADEO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','6','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('ajangulo','ANGULO','BALLARIN','correo@guardiacivil.es','n13453','A1',null,'ACTIVO',to_timestamp('02/02/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('12/01/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','ANTONIO JAVIER','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('slaguia','LAGUIA','FERNANDEZ','correo@guardiacivil.es','n16490','A1',null,'ACTIVO',to_timestamp('01/06/20 06:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/03/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','SEGUNDO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'4','8','36','7','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('silpe','apellido1','apellido2','correo@guardiacivil.es','111111111','A1',null,'ACTIVO',to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'20','Silvia','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_ADMIN','665566544',null,null,'user_alta',null,null,'2','8','17','1','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('pedro','CARRETERO','LIAU','correo@guardiacivil.es','111111111','A1',null,'ACTIVO',to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('05/06/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','PEDRO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_GABINETE','10323',null,null,'user_alta',null,null,'2','8','17','2','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('parribas','ARRIBAS','MARTINEZ','correo@guardiacivil.es','n16603','A1',null,'ACTIVO',to_timestamp('01/02/20 03:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/08/20 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','PEDRO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'4','8','36','7','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('parbona','ARBONA','CAMPOMAR','correo@guardiacivil.es','n25044','A1',null,'ACTIVO',to_timestamp('01/02/20 03:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('12/08/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','PEDRO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_SERVICIO_APOYO','665566544',null,null,'user_alta',null,null,'2','8','17','9','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('mnavarro','NAVARRO','GRAELLS','correo@guardiacivil.es','n19959','A1',null,'ACTIVO',to_timestamp('01/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','MONTSERRAT','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('mfgonzalez','GONZALEZ','FERNANDEZ','correo@guardiacivil.es','n22962','A1',null,'ACTIVO',to_timestamp('01/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','MARCELO FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jsastre','SASTRE','SANCHEZ','correo@guardiacivil.es','n24286','A1',null,'ACTIVO',to_timestamp('01/09/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,to_timestamp('17/01/17 12:46:22,488000000','DD/MM/RR HH24:MI:SS,FF'),'18','JOSE','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,'silpe','4','8','36','4','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jrosas','ROSAS','MARTIN','correo@guardiacivil.es','n19662','A1',null,'ACTIVO',to_timestamp('01/09/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 15:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','JOSE','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jmartinez','MARTINEZ','GANDIA BANCES','correo@guardiacivil.es','n23093','A1',null,'ACTIVO',to_timestamp('01/06/20 06:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/12/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','JAVIER','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'4','8','36','4','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jmanuel','SIERRA','EXOJO','correo@guardiacivil.es','n10704','A1',null,'ACTIVO',to_timestamp('01/01/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/06/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'20','JOSE MANUEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_ADMIN','665566544',null,null,'user_alta',null,null,'2','8','17','3','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jmalberich','ALBERICH','LANDABURU','correo@guardiacivil.es','n22468','A1',null,'ACTIVO',to_timestamp('01/04/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('18/11/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JUAN MANUEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jlcalonge','CALONGE','DELSO','correo@guardiacivil.es','n25583','A1',null,'ACTIVO',to_timestamp('01/02/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/06/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','JOSE LUIS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','9','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jcgonzalez','GONZÃ¿LEZ','VALENCIA','correo@guardiacivil.es','n22465','A1',null,'ACTIVO',to_timestamp('01/04/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/12/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JESUS CARLOS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'4','8','36','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('ciibarguren','IBARGUREN','LEON','correo@guardiacivil.es','n21953','A1',null,'ACTIVO',to_timestamp('01/10/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/07/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'16','CARLOS IGNACIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'3','8','36','8','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('cjsancha','SANCHA','HERRERA','correo@guardiacivil.es','n21129','A1',null,'ACTIVO',to_timestamp('01/09/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','CARLOS JAIME','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('cperez','PEREZ','FERNANDEZ','correo@guardiacivil.es','n23958','A1',null,'ACTIVO',to_timestamp('01/07/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','CONSUELO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('egomez','GOMEZ','ALMERO','correo@guardiacivil.es','n13575','A1',null,'ACTIVO',to_timestamp('01/10/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/07/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'16','ENRIQUE','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'3','8','36','8','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('egomezcorino','CARRILES','CORINO','correo@guardiacivil.es','n21991','A1',null,'ACTIVO',to_timestamp('23/11/20 04:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/08/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,to_timestamp('17/01/17 12:31:30,227000000','DD/MM/RR HH24:MI:SS,FF'),'16','JOSE PEDRO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,'silpe','2','8','17','8','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('faconde','CONDE','FALCON','correo@guardiacivil.es','n14975','A1',null,'ACTIVO',to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/04/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','FRANCISCO ANDRES','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('fdonday','DONDAY','GALVEZ','correo@guardiacivil.es','n22149','A1',null,'ACTIVO',to_timestamp('24/01/20 04:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('23/11/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('fmartcasabas','MARTINEZ','CASBAS','correo@guardiacivil.es','n21694','A1',null,'ACTIVO',to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','4','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jaesteban','ESTEBAN','GOMEZ','correo@guardiacivil.es','n19570','A1',null,'ACTIVO',to_timestamp('01/09/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','JOSE ANTONIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','6','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('japeruyero','PERUYERO','MARTINEZ','correo@guardiacivil.es','n18440','A1',null,'ACTIVO',to_timestamp('20/03/20 08:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('11/08/20 12:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','JOSE ANTONIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','6','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jatristan','TRISTAN','OSTA','correo@guardiacivil.es','n21999','A1',null,'ACTIVO',to_timestamp('01/10/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/07/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,to_timestamp('17/01/17 12:45:59,857000000','DD/MM/RR HH24:MI:SS,FF'),'16','JESUS ANGEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,'silpe','4','8','36','8','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jbarnils','BARNILS','COSTA','correo@guardiacivil.es','n15416','A1',null,'ACTIVO',to_timestamp('01/09/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 15:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JUAN','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jcarranz','ARRANZ','APAOLAZA','correo@guardiacivil.es','n14189','A1',null,'ACTIVO',to_timestamp('10/08/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/05/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JUAN CARLOS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'2','8','17','7','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('msoria','SORIA','TORRALBA','correo@policia.es','n17620','A1',null,'ACTIVO',to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','MIGUEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','6','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('amora','MORA','GALAN','correo@policia.es','n24388','A1',null,'ACTIVO',to_timestamp('01/09/20 06:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','ALBERTO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','4','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('fsempre','SEMPERE','PEÃ‘A','correo@policia.es','n22252','A1',null,'ACTIVO',to_timestamp('01/04/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/06/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','FERNANDO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jicerezo','CEREZO','HERNANDEZ','correo@policia.es','N25342','A1',null,'ACTIVO',to_timestamp('01/01/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/06/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','JOSE IGNACIO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','9','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('fjoliva','OLIVA','GARCIA','correo@policia.es','n22664','A1',null,'ACTIVO',to_timestamp('11/06/20 02:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','FRANCISCO JAVIER','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','4','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jencuentra','ENCUENTRA','BAGUES','correo@policia.es','n13545','A1',null,'ACTIVO',to_timestamp('05/09/99 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('25/09/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JESUS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','7','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jmcervantes','CERVANTES','PARDO','correo@policia.es','n22046','A1',null,'ACTIVO',to_timestamp('27/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JOSE MARIA','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('emartinez','MARTINEZ','ALLER','correo@policia.es','n18342','A1',null,'ACTIVO',to_timestamp('01/09/20 09:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','ELIAS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','6','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jcgalan','GALAN','VIVAR','correo@policia.es','n25655','A1',null,'ACTIVO',to_timestamp('11/04/20 01:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/04/20 13:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','JOSE CARLOS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_SERVICIO_APOYO','665566544',null,null,'user_alta',null,null,'1','8','25','9','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('maserrano','SERRANO','ARGUELLO','correo@policia.es','n20645','A1',null,'ACTIVO',to_timestamp('01/07/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'18','MIGUEL ANGEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','4','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('jmarquez','MARQUES','BERDEJO','correo@policia.es','N15432','A1',null,'ACTIVO',to_timestamp('01/09/20 07:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('11/08/20 10:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','JAVIER','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_ADMIN','665566544',null,null,'user_alta',null,null,'1','8','25','7','3');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('mafan','AFAN','FAJARDO','correo@policia.es','n24639','A1',null,'ACTIVO',to_timestamp('01/01/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('22/06/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'21','MIGUEL','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_SERVICIO_APOYO','665566544',null,null,'user_alta',null,null,'1','8','25','3','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('sfcarrasco','CARRASCO','JIMENEZ','correo@policia.es','n16115','A1',null,'ACTIVO',to_timestamp('10/07/20 00:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 11:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','SALVADOR FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_JEFE_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','7','1');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('cgonzalez','GONZÃ¿LEZ','CASTILLO','correo@policia.es','n15967','A1',null,'ACTIVO',to_timestamp('01/04/20 14:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('01/09/20 15:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'27','CARLOS','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','7','2');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('fvilchews','VILCHES','RENTERO','correo@policia.es','n11718','A1',null,'ACTIVO',to_timestamp('01/09/20 16:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,to_timestamp('17/04/20 15:00:00,000000000','DD/MM/RR HH24:MI:SS,FF'),null,null,null,'28','FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','6','4');
Insert into USERS (USERNAME,PRIM_APELLIDO,SEGUNDO_APELLIDO,CORREO,DOC_IDENTIDAD,CATEGORIA,DESPACHO,ESTADO,FECHA_ALTA,FECHA_BAJA,FECHA_DESTINO_IPSS,FECHA_INACTIVO,FECHA_INGRESO,FECHA_MODIFICACION,NIVEL,NOMBRE,PASSWORD,ROLE,TELEFONO,TFNO_MOVIL_OFICIAL,TFNO_MOVIL_PARTICULAR,USERNAME_ALTA,USERNAME_BAJA,USERNAME_MODIF,ID_CUERPO,ID_DEPARTAMENTO,ID_EMPLEO,ID_PUESTO,ID_CLASE) values ('ipss_progesin','PROGESIN','ipss_progesin','ipss_progesin@interior.es','1111111','A1',null,'ACTIVO',sysdate,null,sysdate,null,null,null,'28','FRANCISCO','$2a$10$tDGyXBpEASeXlAUCdKsZ9u3MBBvT48xjA.v0lrDuRWlSZ6yfNsLve','ROLE_EQUIPO_INSPECCIONES','665566544',null,null,'user_alta',null,null,'1','8','25','6','4');

insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Lérida', LTRIM('0001/2017','0'), 'system', 1, 'I.G.P.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'La Seu D''Urgell', LTRIM('0002/2017','0'), 'system', 1, 'I.G.P.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Lérida', LTRIM('0003/2017','0'), 'system', 1, 'I.G.P.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'La Seu D''Urgell', LTRIM('0004/2017','0'), 'system', 1, 'I.G.P.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Granada', LTRIM('0005/2017','0'), 'system', 1, 'I.G.S.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Granada', LTRIM('0006/2017','0'), 'system', 1, 'I.G.S.','ESTADO_5',4331 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'País Vasco', LTRIM('0007/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Astorga', LTRIM('0008/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Vizcaya', LTRIM('0009/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Astorga', LTRIM('0010/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Álava', LTRIM('0011/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Miranda de Ebro', LTRIM('0012/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Álava', LTRIM('0013/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Miranda de Ebro', LTRIM('0014/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Navarra', LTRIM('0015/2017','0'), 'system', 3, 'I.G.S.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Navarra', LTRIM('0016/2017','0'), 'system', 3, 'I.G.S.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Leganés', LTRIM('0017/2017','0'), 'system', 3, 'I.G.S.','ESTADO_4',4348 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Asturias', LTRIM('0018/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Avilés', LTRIM('0019/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Oviedo', LTRIM('0020/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Avilés', LTRIM('0021/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Burgos', LTRIM('0022/2017','0'), 'system', 2, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Burgos', LTRIM('0023/2017','0'), 'system', 2, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Ceuta', LTRIM('0024/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Torremolinos-Benalmád.', LTRIM('0025/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Ceuta', LTRIM('0026/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Vélez-Málaga', LTRIM('0027/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Málaga', LTRIM('0028/2017','0'), 'system', 3, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Málaga', LTRIM('0029/2017','0'), 'system', 3, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Córdoba', LTRIM('0030/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Linares', LTRIM('0031/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Córdoba', LTRIM('0032/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Martos', LTRIM('0033/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Sevilla', LTRIM('0034/2017','0'), 'system', 2, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'PRIMERO', trunc(sysdate), 'Sevilla', LTRIM('0035/2017','0'), 'system', 2, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'PRIMERO', trunc(sysdate), 'Murcia', LTRIM('0036/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Segovia', LTRIM('0037/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Segovia', LTRIM('0038/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Motril', LTRIM('0039/2017','0'), 'system', 1, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Baza', LTRIM('0040/2017','0'), 'system', 1, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Palencia', LTRIM('0041/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Palencia', LTRIM('0042/2017','0'), 'system', 1, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Centro', LTRIM('0043/2017','0'), 'system', 1, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Melilla', LTRIM('0044/2017','0'), 'system', 1, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Melilla', LTRIM('0045/2017','0'), 'system', 1, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Albacete', LTRIM('0046/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Albacete', LTRIM('0047/2017','0'), 'system', 2, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Móstoles', LTRIM('0048/2017','0'), 'system', 2, 'I.G.S.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Gandía', LTRIM('0049/2017','0'), 'system', 3, 'I.G.P.','ESTADO_4',4376 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Gandía', LTRIM('0050/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Puente de Vallecas', LTRIM('0051/2017','0'), 'system', 3, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Latina', LTRIM('0052/2017','0'), 'system', 3, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Ronda', LTRIM('0053/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Elche', LTRIM('0054/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Ronda', LTRIM('0055/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Calpe', LTRIM('0056/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Antequera', LTRIM('0057/2017','0'), 'system', 3, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Antequera', LTRIM('0058/2017','0'), 'system', 3, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Cuenca', LTRIM('0059/2017','0'), 'system', 2, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Alcázar de San Juan', LTRIM('0060/2017','0'), 'system', 2, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Valdepeñas', LTRIM('0061/2017','0'), 'system', 2, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Cuenca', LTRIM('0062/2017','0'), 'system', 2, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Tarancón', LTRIM('0063/2017','0'), 'system', 2, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Aranda de Duero', LTRIM('0064/2017','0'), 'system', 2, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'SEGUNDO', trunc(sysdate), 'Aranda de Duero', LTRIM('0065/2017','0'), 'system', 2, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'SEGUNDO', trunc(sysdate), 'Valencia', LTRIM('0066/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Palma de Mallorca', LTRIM('0067/2017','0'), 'system', 1, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Manacor', LTRIM('0068/2017','0'), 'system', 1, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Islas Baleares', LTRIM('0069/2017','0'), 'system', 1, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Manacor', LTRIM('0070/2017','0'), 'system', 1, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Gijón', LTRIM('0071/2017','0'), 'system', 1, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Gijón', LTRIM('0072/2017','0'), 'system', 1, 'I.G.S.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Guipúzcoa', LTRIM('0073/2017','0'), 'system', 3, 'I.G.P.','ESTADO_2',4420 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Irún', LTRIM('0074/2017','0'), 'system', 3, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Guipúzcoa', LTRIM('0075/2017','0'), 'system', 3, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Irún', LTRIM('0076/2017','0'), 'system', 3, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Ibiza', LTRIM('0077/2017','0'), 'system', 3, 'I.G.S.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'ibiza', LTRIM('0078/2017','0'), 'system', 3, 'I.G.S.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Pozuelo de Alarcón', LTRIM('0079/2017','0'), 'system', 3, 'I.G.S.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'León', LTRIM('0080/2017','0'), 'system', 1, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Ponferrada', LTRIM('0081/2017','0'), 'system', 1, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'León', LTRIM('0082/2017','0'), 'system', 1, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Ponferrada', LTRIM('0083/2017','0'), 'system', 1, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Las Palmas GC', LTRIM('0084/2017','0'), 'system', 1, 'I.G.S.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Las Palmas GC', LTRIM('0085/2017','0'), 'system', 1, 'I.G.S.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'A Coruña', LTRIM('0086/2017','0'), 'system', 2, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Ferrol-Narón', LTRIM('0087/2017','0'), 'system', 2, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'A Coruña', LTRIM('0088/2017','0'), 'system', 2, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Ferrol', LTRIM('0089/2017','0'), 'system', 2, 'I.G.P.','ESTADO_1',6797 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Alcobendas', LTRIM('0090/2017','0'), 'system', 2, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Chamartín', LTRIM('0091/2017','0'), 'system', 2, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Almería', LTRIM('0092/2017','0'), 'system', 3, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'El Ejido', LTRIM('0093/2017','0'), 'system', 3, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Almería', LTRIM('0094/2017','0'), 'system', 3, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'El Ejido', LTRIM('0095/2017','0'), 'system', 3, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Marbella', LTRIM('0096/2017','0'), 'system', 3, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Marbella', LTRIM('0097/2017','0'), 'system', 3, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Cáceres', LTRIM('0098/2017','0'), 'system', 2, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Mérida', LTRIM('0099/2017','0'), 'system', 2, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Cáceres', LTRIM('0100/2017','0'), 'system', 2, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Mérida', LTRIM('0101/2017','0'), 'system', 2, 'I.G.P.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Valencia', LTRIM('0102/2017','0'), 'system', 2, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'GC', 2017, 'TERCERO', trunc(sysdate), 'Valencia', LTRIM('0103/2017','0'), 'system', 2, 'I.G.S.', 'ESTADO_0',6826 );
insert into inspecciones (id, ambito, anio, cuatrimestre, fecha_alta, nombre_unidad, numero,username_alta, id_equipo, tipo_inspeccion,estado_inspeccion,id_municipio ) values (seq_inspeccion.nextval, 'PN', 2017, 'TERCERO', trunc(sysdate), 'Tenerife', LTRIM('0104/2017','0'), 'system', 3, 'I.G.P.', 'ESTADO_0',6826 );


INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (1,'ANEXOS AL INFORME');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (2,'ÁREA OPERATIVA');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (3,'ÁREAS ADMINISTRATIVA Y DE APOYO');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (4,'AUDIO');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (5,'CONTROL DE ACTIVIDAD');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (6,'CUESTIONARIO');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (7,'DATOS ESTADISTICOS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (8,'DOCUMENTACIÓN ENTRADA IPSS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (9,'DOCUMENTACIÓN SALIDA IPSS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (10,'FICHA SEGUIMIENTO Y CONTROL');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (11,'HIPEST / SIDENPOL');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (12,'HISTORICO INFORMES');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (13,'IMAGEN');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (14,'INFORME');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (15,'INFRAESTRUCTURAS E INSTALACIONES');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (16,'LIBROS OFICIALES');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (17,'NORMA  INTERNA');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (18,'OTROS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (19,'PROGRAMA ESTADÍSTICO DE SEGURIDAD');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (20,'QUEJAS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (21,'RECURSOS HUMANOS');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (22,'RECURSOS MATERIALES');
INSERT INTO TIPO_DOCUMENTO (ID,NOMBRE) VALUES (23,'VIDEO');




