insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLAPLANTILLAPN', 'PUESTO DE TRABAJO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLAPLANTILLAPN', 'ESC/CAT/GRUPO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLAPLANTILLAPN', 'DOTACIÓN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLAPLANTILLAPN', 'COBERTURA.TITULAR');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'TABLAPLANTILLAPN', 'COBERTURA.ACCTAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'TABLAPLANTILLAPN', 'COBERTURA.DIFERENCIA');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'GABINETE TÉCNICO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'PRENSA Y RELACIONES PUBLICAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'UIP');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'UTI');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'REGIMEN DISCIPLINARIO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'SISTEMAS ESPECIALES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'BOA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'HELICOPTEROS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'ESTADISTICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'INSPECCIÓN CENTRAL GUARDIA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'COMISARÍAS DE DISTRITO (incluir ODAC)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'COORDINADORES DE SERVICIO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'FORMACIÓN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'PERSONAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'UNIDAD REGIONAL DE SANIDAD');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'INFRAESTRUCTURA-(Mantenimiento)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'GESTIÓN ECONÓMICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'ARMAMENTO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'AUTOMOCIÓN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'TELECOMUNICACIONES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila10', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'INFORMÁTICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila11', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'VESTUARIO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila12', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'ASISTENCIA LETRADA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila13', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'ARCHIVO GENERAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila14', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'DNI- PASAPORTES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila15', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'DOCUMENTACIÓN EXTRANJEROS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila16', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'PRL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila17', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'OTROS (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOGENERALPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'SECCION OPERATIVA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'GRUPOS OPERATIVOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'SECCIÓN TÉCNICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'TEDAX-NRBQ');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'UDYCO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'UDEV');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'UDEF');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'UFAM (SAM, GRUME y UPAP)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'SECCIÓN TÉCNICA - INFORMES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'JUEGO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'UNIDAD ADSCRITA TRIBUNALES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'OTROS (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'GOES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SEGURIDAD PRIVADA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'PARTICIPACIÓN CIUDADANA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'ATENCIÓN CIUDADANA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'UNIDAD PROTECCION Y SEGURIDAD');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'CONDUCCIONES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SECTOR MOVIL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'UPR');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila10', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SALA 091');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila11', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'GUIAS CANINOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila12', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'ESCOLTAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila13', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SUBSUELO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila14', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'CABALLERÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila15', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'OTROS (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'SERVICIO OPERATIVO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'SECCIÓN TÉCNICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'SECCIÓN OPERATIVA UCRIF');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'GRUPOS OPERATIVOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'CIE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'OTROS (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'SECRETARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'LABORATORIO ADN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'INSPECCIONES OCULARES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'CRIMANLISTICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'IDENTIFICACIÓN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'OTROS (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'AEROPUERTO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'TOTAL FUNCIONARIOS POLICIALES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'TOTAL GENERAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'C. PRAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'FAC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'TEC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZPERSONALAUSENTEPN', 'SUSPENDIDOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZPERSONALAUSENTEPN', 'ENFERMOS LARGA DURACION');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZPERSONALAUSENTEPN', 'CURSOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZPERSONALAUSENTEPN', 'COMISION SERVICIO, ATFs');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZPERSONALAUSENTEPN', 'LICENCIA MATERNIDAD');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZPERSONALAUSENTEPN', 'LIBERADO SINDICAL (tiempo completo)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZPERSONALAUSENTEPN', 'TOTAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZPERSONALAUSENTEPN', 'C.PPAL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZPERSONALAUSENTEPN', 'COM.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZPERSONALAUSENTEPN', 'I. JEFE');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZPERSONALAUSENTEPN', 'INSP.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZPERSONALAUSENTEPN', 'SUBIN.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZPERSONALAUSENTEPN', 'OFIC.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZPERSONALAUSENTEPN', 'POL.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZPERSONALAUSENTEPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZPERSONALPORGRUPOSPN', 'JEFATURA COMISARÍA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZPERSONALPORGRUPOSPN', 'JEFATURA REG. OPERACIONES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZPERSONALPORGRUPOSPN', 'COMISARÍA PROVINCIAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZPERSONALPORGRUPOSPN', 'COMISARÍA PROVINCIAL (Comisarías de Distrito )');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL (PERSONAL)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(FORMACIÓN)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(INFORMÁTICA)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(GESTIÓN ECONÓMICA)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila10', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(DNI- PASAPORTES)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila11', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(DOCUMENTACIÓN EXTRANJEROS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila12', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(ARCHIVO GENERAL)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila13', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(ARMAMENTO)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila14', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(AUTOMOCIÓN)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila15', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(TELECOMUNICACIONES)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila16', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(VESTUARIO)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila17', 'MATRIZPERSONALPORGRUPOSPN', 'SECRETARÍA GENERAL(MANTENIMIENTO)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila18', 'MATRIZPERSONALPORGRUPOSPN', 'INFORMACIÓN');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila19', 'MATRIZPERSONALPORGRUPOSPN', 'POLICÍA JUDICIAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila20', 'MATRIZPERSONALPORGRUPOSPN', 'SEGURIDAD CIUDADANA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila21', 'MATRIZPERSONALPORGRUPOSPN', 'EXTRANJERÍA Y FRONTERAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila22', 'MATRIZPERSONALPORGRUPOSPN', 'POLICÍA  CIENTÍFICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila23', 'MATRIZPERSONALPORGRUPOSPN', 'PUESTOS FRONTERIZOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila24', 'MATRIZPERSONALPORGRUPOSPN', 'TOTAL GENERAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZPERSONALPORGRUPOSPN', 'GRUPO A');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZPERSONALPORGRUPOSPN', 'GRUPO B');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZPERSONALPORGRUPOSPN', 'ADTVOS.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZPERSONALPORGRUPOSPN', 'AUXS.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZPERSONALPORGRUPOSPN', 'P.  LABORAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZPERSONALPORGRUPOSPN', 'TOTAL');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE SUPERIOR');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE REGIONAL OPERACIONES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZEQUIPODIRECTIVOPN', 'COMISARIO PROVINCIAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZEQUIPODIRECTIVOPN', 'SECRETARIO GENERAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE B.P.S.C.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE B.P.P.J.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE B.P.E. y F.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE B.P.I.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE B.P.P.C.');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila10', 'MATRIZEQUIPODIRECTIVOPN', 'JEFE PUESTO FRONTERIZO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZEQUIPODIRECTIVOPN', 'Categoría');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZEQUIPODIRECTIVOPN', 'NOMBRE Y APELLIDOS (E-mail y teléfono oficial');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZEQUIPODIRECTIVOPN', 'ANTIGÜEDAD EN LA PLANTILLA (AÑOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZEQUIPODIRECTIVOPN', 'ANTIGÜEDAD EN LA PLANTILLA (MESES)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZEQUIPODIRECTIVOPN', 'ANTIGÜEDAD EN EL CARGO (AÑOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZEQUIPODIRECTIVOPN', 'ANTIGÜEDAD EN EL CARGO (MESES)');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'AÑO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'COMISARIO PRINCIPAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'COMISARIO');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'INSPECTORES JEFES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'INSPECTORES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'SUBINSPECTORES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'OFICIALES');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'POLICÍAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo09', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'SUMAN (FACULTATIVOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo10', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'SUMAN (TÉCNICOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo11', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'SUMAN (2ª  ACTIVIDAD)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo12', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'TOTAL C.N.P. (CUERPOS GENERALES)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo13', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'TOTAL C.N.P. (PERSONAL LABORAL)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo14', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'TOTAL GENERAL (TOTAL CC.GG. Y P. LAB.)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'HACE CINCO AÑOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'HACE CUATRO AÑOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'HACE TRES AÑOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'HACE DOS AÑOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN', 'AÑO ANTERIOR');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZCONSULTASMEDPN', 'Consultas médicas');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZCONSULTASMEDPN', 'Consultas de enfermería (Curas)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZCONSULTASMEDPN', 'Consultas de enfermería (Inyectables)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZCONSULTASMEDPN', 'Consultas de enfermería (Tensión arterial)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZCONSULTASMEDPN', 'Consultas de enfermería (Electrocardiogramas)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZCONSULTASMEDPN', 'Consultas de enfermería (Otras (especificar))');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZCONSULTASMEDPN', 'Consultas psicología clínica');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila08', 'MATRIZCONSULTASMEDPN', 'Prescripciones y tratamientos médicos');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila09', 'MATRIZCONSULTASMEDPN', 'Reconocimientos y asistencias a detenidos en calabozos');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila10', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios ()');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila11', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios ()');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila12', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios ()');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila13', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios ()');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila14', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios ()');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila15', 'MATRIZCONSULTASMEDPN', 'Reconocimientos a funcionarios (Otros (especificar))');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila16', 'MATRIZCONSULTASMEDPN', 'Recetas');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila17', 'MATRIZCONSULTASMEDPN', 'Control Incapacidad Temporal (Visitas Hospitalarias)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila18', 'MATRIZCONSULTASMEDPN', 'Control Incapacidad Temporal (Visitas domiciliarias)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila19', 'MATRIZCONSULTASMEDPN', 'Control Incapacidad Temporal (Reconocimientos IT)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila20', 'MATRIZCONSULTASMEDPN', 'Control Incapacidad Temporal (Citaciones funcionarios)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila21', 'MATRIZCONSULTASMEDPN', 'Control Incapacidad Temporal (Otras (Especificar))');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila22', 'MATRIZCONSULTASMEDPN', 'Informes (Médicos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila23', 'MATRIZCONSULTASMEDPN', 'Informes (Clínicos laborales)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila24', 'MATRIZCONSULTASMEDPN', 'Informes (Accidentes servicio)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila25', 'MATRIZCONSULTASMEDPN', 'Informes (Licencias enfermedad)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila26', 'MATRIZCONSULTASMEDPN', 'Informes (Causalidad)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila27', 'MATRIZCONSULTASMEDPN', 'Informes (Retirada de armas)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila28', 'MATRIZCONSULTASMEDPN', 'Informes (Autorización residencia)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila29', 'MATRIZCONSULTASMEDPN', 'Informes (Expedientes de incapacidad)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila30', 'MATRIZCONSULTASMEDPN', 'Informes (Otros (especificar))');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila31', 'MATRIZCONSULTASMEDPN', 'Acompañamiento ejercicios de tiro');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila32', 'MATRIZCONSULTASMEDPN', 'Vacunaciones');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila33', 'MATRIZCONSULTASMEDPN', 'Control higiénico sanitario en vehículos policiales');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila34', 'MATRIZCONSULTASMEDPN', 'Educación sanitaria');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila35', 'MATRIZCONSULTASMEDPN', 'Otras actividades (especificar)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila36', 'MATRIZCONSULTASMEDPN', 'TOTAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZCONSULTASMEDPN', 'HACE DOS AÑOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZCONSULTASMEDPN', 'AÑO ANTERIOR');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZINCAPACIDADTEMPESCALA', 'Superior');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZINCAPACIDADTEMPESCALA', 'Ejecutiva');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZINCAPACIDADTEMPESCALA', 'Subinspección');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZINCAPACIDADTEMPESCALA', 'Básica');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZINCAPACIDADTEMPESCALA', 'TOTAL ');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZINCAPACIDADTEMPESCALA', 'Morbilidad (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZINCAPACIDADTEMPESCALA', 'Morbilidad (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZINCAPACIDADTEMPESCALA', 'Siniestralidad (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZINCAPACIDADTEMPESCALA', 'Siniestralidad (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZINCAPACIDADTEMPESCALA', 'Psíquica (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZINCAPACIDADTEMPESCALA', 'Psíquica (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZINCAPACIDADTEMPESCALA', 'Inasistencias (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZINCAPACIDADTEMPESCALA', 'Inasistencias (Días perdidos)');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Información');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Policía Judicial');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Seguridad Ciudadana');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Extranjería y Documentación');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Científica');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila06', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Otras Unidades Comisaría');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila07', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'TOTAL ');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Morbilidad (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Morbilidad (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Siniestralidad (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Siniestralidad (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Psíquica (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Psíquica (Días perdidos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo07', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Inasistencias (Núm. procesos)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo08', 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL', 'Inasistencias (Días perdidos)');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLAINASISTENCIASPN', '1 día');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLAINASISTENCIASPN', '2 días');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLAINASISTENCIASPN', '3 días');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLAINASISTENCIASPN', '4 días');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'TABLAINASISTENCIASPN', '+ 4 días');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLALIMITACIONCATEGORIA', 'Categoría/Empleo');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLALIMITACIONCATEGORIA', 'Destino / Actividad que desarrolla');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLALIMITACIONCATEGORIA', 'Servicio / baja');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLALIMITACIONCATEGORIA', 'Limitación');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLATRIBMEDICOCATEGORIAPN', 'Categoría');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLATRIBMEDICOCATEGORIAPN', 'Destino');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLATRIBMEDICOCATEGORIAPN', 'Fecha de baja');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLATRIBMEDICOCATEGORIAPN', 'Fecha propuesta examen');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'TABLATRIBMEDICOCATEGORIAPN', 'Fecha pase Tribunal');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo06', 'TABLATRIBMEDICOCATEGORIAPN', 'Resultado');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLARESIDENCIABAJACATEGORIA', 'Categoría/Empleo');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLARESIDENCIABAJACATEGORIA', 'Fecha de baja');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLARESIDENCIABAJACATEGORIA', 'Autorizado a residir en');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLARESIDENCIABAJACATEGORIA', 'Autorizado a residir desde');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLARESIDENCIADESTINOCATEGORIA', 'Categoría/Empleo');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLARESIDENCIADESTINOCATEGORIA', 'Destino');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLARESIDENCIADESTINOCATEGORIA', 'Fecha de baja');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLARESIDENCIADESTINOCATEGORIA', 'Autorizado a residir desde');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLAOTROSMOTIVOSCATEGORIA', 'Categoría/Empleo');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLAOTROSMOTIVOSCATEGORIA', 'Motivos');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLAOTROSMOTIVOSCATEGORIA', 'Jornadas/días en esa situación');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZFORMACIONREALIZADA', 'FORMACIÓN ELECTRÓNICA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZFORMACIONREALIZADA', 'FORMACIÓN PRESENCIAL');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZFORMACIONREALIZADA', 'CURSOS (CENTRALIZADOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZFORMACIONREALIZADA', 'CURSOS (DESCENTRALIZADOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZFORMACIONREALIZADA', 'ALUMNOS (INFORMADOS)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZFORMACIONREALIZADA', 'ALUMNOS (CONCEDIDOS)');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLACURSOSUBICACION', 'CURSOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLACURSOSUBICACION', 'ACTIVIDAD IMPARTIDA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLACURSOSUBICACION', 'FECHAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLACURSOSUBICACION', 'Nº ALUMNOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'TABLACURSOSUBICACION', 'UBICACIÓN');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'TABLACURSOS', 'CURSOS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'TABLACURSOS', 'ACTIVIDAD IMPARTIDA');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'TABLACURSOS', 'FECHAS');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'TABLACURSOS', 'Nº ALUMNOS');

insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila01', 'MATRIZTIROPERSONALACTIVOPN', 'Superior');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila02', 'MATRIZTIROPERSONALACTIVOPN', 'Ejecutiva');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila03', 'MATRIZTIROPERSONALACTIVOPN', 'Subinspección');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila04', 'MATRIZTIROPERSONALACTIVOPN', 'Básica');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('nombreFila05', 'MATRIZTIROPERSONALACTIVOPN', 'TOTAL');


insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo01', 'MATRIZTIROPERSONALACTIVOPN', 'Total plantilla');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo02', 'MATRIZTIROPERSONALACTIVOPN', 'Numérico del personal (1º trimestre)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo03', 'MATRIZTIROPERSONALACTIVOPN', 'Numérico del personal (2º trimestre)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo04', 'MATRIZTIROPERSONALACTIVOPN', 'Numérico del personal (3º trimestre)');
insert into CONFIG_RESPUESTAS_CUESTIONARIO (CLAVE,SECCION,VALOR) values ('campo05', 'MATRIZTIROPERSONALACTIVOPN', 'Numérico del personal (4º trimestre)');











--insert modelo RRHH DE LA POLICIA NACIONAL

Insert into MODELOSCUESTIONARIOS (ID,CODIGO,DESCRIPCION) values (SEQ_MODELOSCUESTIONARIOS.NEXTVAL,'RRHH_PN','DOTACIÓN Y GESTIÓN DE RECURSOS HUMANOS');

--insert área

Insert into  areascuestionario (id, nombre_area, id_cuestionario, orden) values (SEQ_AREASCUESTIONARIOS.NEXTVAL, 'DOTACIÓN Y GESTIÓN DE RECURSOS HUMANOS', SEQ_MODELOSCUESTIONARIOS.CURRVAL, 0);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. JEFATURA SUPERIOR DE POLICIA.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN', 0);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. COMISARIA PROVINCIAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',1);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. SECRETARIA GENERAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',2);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. BRIGADA PROVINCIAL SEGURIDAD CIUDADANA.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',3);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. BRIGADA PROVINCIAL POLICÍA JUDICIAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',4);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. BRIGADA PROVINCIAL EXTRANJERÍA Y FRONTERAS.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',5);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. BRIGADA PROVINCIAL INFORMACIÓN.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',6);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. BRIGADA PROVINCIAL POLICÍA CIENTÍFICA.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',7);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. PUESTO FRONTERIZO (sólo si está integrado en el CPT propio de la Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',8);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'PLANTILLA Y DISTRIBUCIÓN. COBERTURA DEL CATÁLOGO. TOTAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAPLANTILLAPN',9);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO (JEFE SUPERIOR).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOJEFESUPERIORPN',10);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. (JEFE REG. OPERACIONES).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOJEFEOPERACIONESPN',11);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. (COMISARIA PROVINCIAL).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOPROVINCIALPN',12);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. (SECRETARÍA GENERAL).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOGENERALPN',13);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. B.P. INFORMACIÓN (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOINFORMACIONPN',14);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. B. POLICÍA JUDICIAL (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOJUDICIALPN',15);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. B. SEG. CIUDADANA (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOSEGCIUDADANAPN',16);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. B. EXTR. y FRONT. (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOFRONTERAPN',17);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. B. POL. CIENTÍFICA (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOPOLCIENTIFICAPN',18);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. PUESTO FRONTERIZO (Jefatura).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOPUESTOFRONTPN',19);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. TOTAL FUNCIONARIOS POLICIALES.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOTOTALFUNCIONARIOPN',20);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL POLICÍA NACIONAL EN ACTIVO. TOTAL GENERAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZDISTRIBUCIONACTIVOTOTALGENERALPN',21);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Personal  ausente en la Unidad por las siguientes causas:', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZPERSONALAUSENTEPN',22);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Personal en prácticas en la Plantilla. DETALLAR POR ESCALA EJECUTIVA Y BÁSICA.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',23);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Personal  en situación de segunda actividad con destino: DETALLAR CATEGORIA, PUESTO DE TRABAJO Y DESTINO.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',24);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'DISTRIBUCIÓN DE PERSONAL. CUERPOS GENERALES Y PERSONAL LABORAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZPERSONALPORGRUPOSPN',25);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'EQUIPO DIRECTIVO. RELACIÓN NOMINAL.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZEQUIPODIRECTIVOPN',26);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Evolución numérica del personal en la plantilla (a 31 de diciembre de cada año)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZEVOLUCIONEQUIPODIRECTIVOPN',27);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Catálogo de puestos de trabajo: El vigente catálogo asignado se considera suficiente o insuficiente. En este último caso explicar motivación y propuestas efectuadas para su modificación.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',28);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Efectivos reales: El grado de cobertura de la plantilla se considera adecuado en todas sus categorías. En caso negativo motivar.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',29);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Necesidades creación de nuevas Unidades o Especialidades. Motivación. Existencia de propuestas elevadas a Órganos Centrales.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',30);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
La RPT de  Cuerpos Generales, Personal Laboral se considera suficiente o insuficiente. En este último caso explicar motivación y propuestas efectuadas para su modificación.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',31);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Dificultad existente para cubrir las vacantes (especificar por Categorías).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',32);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Problemática y causas relativas al absentismo.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',33);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Otras cuestiones dignas de reseñar.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',34);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Valoración de los responsables de la Unidad sobre los puntos anteriores. 
Otras cuestiones dignas de reseñar.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',34);


insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Horarios de servicio (Personal de Gestión).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'INPUT',35);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Horarios de servicio (Personal Operativo).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'INPUT',36);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Horarios de servicio.
Problemática que plantea la implantación de la nueva normativa sobre Jornada laboral. Precisar el turno que se aplica en los servicios de 24 horas (ODAC, GAC, Sala 091, Seguridad y custodia y coordinadores de servicio).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TEXTAREA',37);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Unidad de Sanidad. Responsable.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'INPUT',38);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Unidad de Sanidad. Tiempo en el cargo (Años y meses).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'INPUT',39);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Unidad de Sanidad. Personal, horarios y turnos.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',40);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Unidad de Sanidad. Actividad y rendimiento.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',41);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Unidad de Sanidad. Actividad y rendimiento.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZCONSULTASMEDPN',42);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Absentismo.
El Jefe de la Unidad Sanitaria elaborará un informe individualizado en el que se aborden, al menos, los siguientes aspectos:
Evolución de los parámetros de absentismo de causa médica. Estudio de su repercusión por escalas y categorías, así como por áreas funcionales. Problemática singular. Incidencia de las inasistencias y mecanismos dispuestos para el efectivo control en su registro (se adjuntan a continuación tablas que se proponen para la recogida de la información).
Actividad desarrollada por las Unidades Médicas de Seguimiento del INSS en el control de los procesos de incapacidad temporal. Análisis cuantitativo y cualitativo. Disponibilidad de acceso a la aplicación MUFACE.
Problemática y necesidades de la Servicio Sanitario. Especial referencia a la prestación del servicio a las Unidades ubicadas en otras plantillas de la Provincia.
Coordinación de actuaciones con los órganos de personal y retribuciones correspondientes, en aplicación de las medidas dispuestas en Real Decreto-Ley 20/2012, de 13 de julio, de medidas para garantizar la estabilidad presupuestaria y de fomento de la competitividad (artículo 9).
', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',43);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. 
Datos de incapacidad temporal por escalas. Año en curso.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZINCAPACIDADTEMPESCALA',44);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. 
Datos de incapacidad temporal por escalas. Año anterior.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZINCAPACIDADTEMPESCALA',45);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. 
Datos de incapacidad temporal por áreas funcionales. Año en curso.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL',46);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. 
Datos de incapacidad temporal por áreas funcionales. Año anterior.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZINCAPACIDADTEMPAREAFUNCIONAL',47);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta.
Control de las inasistencias. Situaciones registradas.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAINASISTENCIASPN',48);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta.
Número de procesos de incapacidad temporal cuya duración supera los periodos que se indican (Días perdidos que acumulan estos procesos). Se reflejarán los datos de las situaciones existentes en el momento de su emisión, señalando expresamente su fecha.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTOINPUT',49);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta.
Cómputo del Personal por categorías (sin datos personales) que tenga reconocida alguna limitación para la prestación del servicio, expresiva del destino, si presta servicio o si permanece de baja, así como la limitación concreta. Referido a las situaciones vigentes a fecha de emisión de este informe.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLALIMITACIONCATEGORIA',50);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. Año en curso.
Cómputo del Personal por categorías (sin datos personales) derivado a Tribunales Médicos (también quienes se encuentren pendientes).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLATRIBMEDICOCATEGORIAPN',51);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. Año anterior.
Cómputo del Personal por categorías (sin datos personales) derivado a Tribunales Médicos (también quienes se encuentren pendientes).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLATRIBMEDICOCATEGORIAPN',52);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. Año en curso.
Cómputo del Personal por categorías (sin datos personales) en situación de incapacidad temporal para el servicio de esa Jefatura Superior, autorizado a residir en otras demarcaciones, con indicación de la fecha de la baja. Referido a las situaciones vigentes a fecha de emisión de este informe.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLARESIDENCIABAJACATEGORIA',53);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta. Año anterior.
Cómputo del Personal por categorías (sin datos personales) en situación de incapacidad temporal para el servicio de esa Jefatura Superior, autorizado a residir en otras demarcaciones, con indicación de la fecha de la baja. Referido a las situaciones vigentes a fecha de emisión de este informe.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLARESIDENCIABAJACATEGORIA',54);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta.
Cómputo del Personal por categorías (sin datos personales) en situación de incapacidad temporal, pertenecientes a otras Unidades, autorizado a residir en la demarcación de esa Jefatura Superior, con indicación de la fecha de la baja. Referido a las situaciones vigentes a fecha de emisión de este informe.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLARESIDENCIADESTINOCATEGORIA',55);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Modelo de recogida de información propuesta.
Cómputo del Personal por categorías (sin datos personales) que por motivos distintos a los anteriores no ha prestado su actividad en la Unidad de pertenencia (suspensos funciones, licencias, días sindicales,…, distintas a vacaciones, asuntos particulares).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLAOTROSMOTIVOSCATEGORIA',56);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Actividades realizadas (Último año).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZFORMACIONREALIZADA',57);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Actividades realizadas (Año anterior).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZFORMACIONREALIZADA',58);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Cursos centralizados.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOS',59);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Cursos descentralizados por ubicación.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOSUBICACION',60);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Cursos de formación electrónica (on line).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOS',61);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Otros cursos o convocatorias (Seguridad Privada, etc.)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOS',62);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Otros cursos o convocatorias (Seguridad Privada, etc.)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOS',63);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Otros cursos o convocatorias (Seguridad Privada, etc.)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'TABLACURSOS',64);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Necesidades en materia de especialización (motivar).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',65);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Necesidades en materia de actualización (normativa interna y disposiciones relacionadas con la operatividad).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',66);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Alumnos (funcionarios en prácticas). Problemática en materia de formación (material didáctico, profesorado, experiencia del funcionario que les acompaña en el servicio, etc.)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',67);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Problemática en materia de formación (infraestructura, material didáctico, medios materiales, profesorado).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',68);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Cursos on-line. Problemática que plantea.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',69);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Formación centralizada (demanda cuantificada y peticiones no cubiertas)', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',70);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Formación descentralizada (demanda cuantificada y peticiones no cubiertas).', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',71);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Formación. Otras cuestiones dignas de reseñar.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'ADJUNTO',72);

insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Plan de tiro. Personal en situación de Activo. Último año.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZTIROPERSONALACTIVOPN',73);
insert into  preguntascuestionario (ID,PREGUNTA,Id_area,tipo_respuesta, orden) Values (SEQ_PREGUNTASCUESTIONARIO.NEXTVAL, 'Plan de tiro. Personal en situación de Activo. Año anterior.', SEQ_AREASCUESTIONARIOS.CURRVAL, 'MATRIZTIROPERSONALACTIVOPN',74);

commit;





































