INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
1,sysdate,'system','PN',2018,1,'I.G.P.','PRIMERO',2,'Sagunto','7183');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
2,sysdate,'system','PN','2018',1,'I.G.P.','PRIMERO',2,'Burjassot-Godella','7044');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
3,sysdate,'system','PN',2018,1,'I.G.P.','PRIMERO',2,'Paterna','7149');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
4,sysdate,'system','GC','2018',1,'I.G.P.','PRIMERO',4,'Requena','7176');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
5,sysdate,'system','GC',2018,1,'I.G.P.','PRIMERO',4,'Lliria','6219');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
6,sysdate,'system','PN','2018',1,'I.G.S.','PRIMERO',3,'Córdoba','2063');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
7,sysdate,'system','GC',2018,1,'I.G.S.','PRIMERO',6,'Córdoba','2063');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
8,sysdate,'system','PN','2018',1,'I.G.S.','PRIMERO',2,'Linares','3549');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
9,sysdate,'system','GC',2018,1,'I.G.S.','PRIMERO',4,'Martos','3554');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
10,sysdate,'system','PN','2018',2,'I.G.P.','PRIMERO',2,'Xátiva','7225');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
11,sysdate,'system','PN',2018,2,'I.G.P.','PRIMERO',2,'Denia','201');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
12,sysdate,'system','GC','2018',2,'I.G.P.','PRIMERO',4,'Xátiva','7225');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
13,sysdate,'system','GC',2018,2,'I.G.P.','PRIMERO',4,'Ibi','216');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
14,sysdate,'system','PN','2018',2,'I.G.S.','PRIMERO',3,'Lleida','3916');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
15,sysdate,'system','PN',2018,2,'I.G.S.','PRIMERO',10,'La Seu d'Urgell','3986');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
16,sysdate,'system','GC','2018',2,'I.G.S.','PRIMERO',6,'Lleida','3916');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
17,sysdate,'system','GC',2018,2,'I.G.S.','PRIMERO',4,'La Seu d'Urgell','3986');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
18,sysdate,'system','PN','2018',3,'I.G.P.','PRIMERO',2,'Álcalá de Guadaira','6152');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
19,sysdate,'system','PN',2018,3,'I.G.P.','PRIMERO',2,'Camas','6075');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
20,sysdate,'system','PN','2018',3,'I.G.P.','PRIMERO',2,'Coria del Rio','6089');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
21,sysdate,'system','GC',2018,3,'I.G.P.','PRIMERO',4,'Utrera','6152');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
22,sysdate,'system','GC','2018',3,'I.G.P.','PRIMERO',4,'Carmona','6079');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
23,sysdate,'system','PN',2018,3,'I.G.S.','PRIMERO',2,'Torremolinos-Benalm.','4544');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
24,sysdate,'system','GC','2018',3,'I.G.S.','PRIMERO',4,'Vélez-Málaga','4548');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
25,sysdate,'system','PN',2018,4,'I.G.P.','PRIMERO',2,'Úbeda','3583');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
26,sysdate,'system','GC','2018',4,'I.G.P.','PRIMERO',4,'Baeza','3505');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
27,sysdate,'system','GC',2018,4,'I.G.P.','PRIMERO',4,'Beas de Segura','3508');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
28,sysdate,'system','GC','2018',4,'I.G.P.','PRIMERO',4,'La Carolina','3519');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
29,sysdate,'system','GC',2018,4,'I.G.P.','PRIMERO',4,'Jaén','6543');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
30,sysdate,'system','PN','2018',4,'I.G.S.','PRIMERO',3,'Araba','46');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
31,sysdate,'system','GC',2018,4,'I.G.S.','PRIMERO',6,'Araba','46');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
32,sysdate,'system','PN','2018',4,'I.G.S.','PRIMERO',2,'Miranda de Ebro','1342');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
33,sysdate,'system','GC',2018,4,'I.G.S.','PRIMERO',4,'Miranda de Ebro','1342');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
34,sysdate,'system','PN','2018',5,'I.G.P.','PRIMERO',2,'Vilagarcía de Arousa','5327');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
35,sysdate,'system','PN',2018,5,'I.G.P.','PRIMERO',2,'Marín','5293');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
36,sysdate,'system','GC','2018',5,'I.G.P.','PRIMERO',4,'Pontevedra','5309');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
37,sysdate,'system','GC',2018,5,'I.G.P.','PRIMERO',4,'Vilagarcía de Arousa','5327');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
38,sysdate,'system','GC','2018',5,'I.G.P.','PRIMERO',4,'Lalín','5291');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
39,sysdate,'system','PN',2018,5,'I.G.S.','PRIMERO',7,'Asturias','5006');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
40,sysdate,'system','GC','2018',5,'I.G.S.','PRIMERO',6,'Oviedo','5006');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
41,sysdate,'system','PN',2018,5,'I.G.S.','PRIMERO',2,'Avilés','4967');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
42,sysdate,'system','GC','2018',5,'I.G.S.','PRIMERO',4,'Avilés','4967');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
43,sysdate,'system','PN',2018,6,'I.G.P.','PRIMERO',2,'Puerto del Rosario','5250');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
44,sysdate,'system','PN','2018',6,'I.G.P.','PRIMERO',2,'Telde','5258');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
45,sysdate,'system','GC',2018,6,'I.G.P.','PRIMERO',4,'Puerto del Rosario','5250');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
46,sysdate,'system','GC','2018',6,'I.G.P.','PRIMERO',4,'Vecindario','8113');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
47,sysdate,'system','PN',2018,6,'I.G.S.','PRIMERO',7,'País Vasco','7484');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
48,sysdate,'system','GC','2018',6,'I.G.S.','PRIMERO',6,'Bilbao','7484');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
49,sysdate,'system','PN',2018,6,'I.G.S.','PRIMERO',2,'Astorga','3600');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
50,sysdate,'system','GC','2018',6,'I.G.S.','PRIMERO',4,'Astorga','3600');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
51,sysdate,'system','PN',2018,7,'I.T_CIE','PRIMERO',5,'Barcelona','881');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
52,sysdate,'system','PN','2018',1,'I.G.P.','SEGUNDO',2,'Quart de Poblet-Manises','7166');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
53,sysdate,'system','PN',2018,1,'I.G.P.','SEGUNDO',2,'Mislata','7128');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
54,sysdate,'system','PN','2018',1,'I.G.P.','SEGUNDO',2,'Xirivella-Aldaia-Alaquas','7228');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
55,sysdate,'system','PN',2018,1,'I.G.P.','SEGUNDO',2,'Torrent','7208');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
56,sysdate,'system','PN','2018',1,'I.G.S.','SEGUNDO',3,'Albacete','54');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
57,sysdate,'system','GC',2018,1,'I.G.S.','SEGUNDO',6,'Albacete','54');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
58,sysdate,'system','PN','2018',2,'I.G.P.','SEGUNDO',2,'Alcantarilla','4559');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
59,sysdate,'system','PN',2018,2,'I.G.P.','SEGUNDO',2,'Cartagena','4571');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
60,sysdate,'system','GC','2018',2,'I.G.P.','SEGUNDO',4,'Caravaca de la Cruz','4570');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
61,sysdate,'system','GC',2018,2,'I.G.P.','SEGUNDO',4,'Cartagena','4571');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
62,sysdate,'system','PN','2018',2,'I.G.S.','SEGUNDO',3,'Segovia','6020');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
63,sysdate,'system','GC',2018,2,'I.G.S.','SEGUNDO',6,'Segovia','6020');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
64,sysdate,'system','PN','2018',3,'I.G.P.','SEGUNDO',2,'Dos Hermanas','6094');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
65,sysdate,'system','PN',2018,3,'I.G.P.','SEGUNDO',2,'Écija','6095');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
66,sysdate,'system','PN','2018',3,'I.G.P.','SEGUNDO',2,'Morón de la Frontera','6122');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
67,sysdate,'system','GC',2018,3,'I.G.P.','SEGUNDO',4,'Osuna','6125');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
68,sysdate,'system','GC','2018',3,'I.G.P.','SEGUNDO',4,'Sánlucar La Mayor','6145');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
69,sysdate,'system','PN',2018,3,'I.G.S.','SEGUNDO',2,'Ronda','4537');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
70,sysdate,'system','GC','2018',3,'I.G.S.','SEGUNDO',4,'Ronda','4537');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
71,sysdate,'system','PN',2018,3,'I.G.S.','SEGUNDO',2,'Elche','203');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
72,sysdate,'system','GC','2018',3,'I.G.S.','SEGUNDO',4,'Calpe','187');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
73,sysdate,'system','PN',2018,4,'I.G.P.','SEGUNDO',2,'Baza','2691');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
74,sysdate,'system','GC','2018',4,'I.G.P.','SEGUNDO',4,'Guadix','2747');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
75,sysdate,'system','GC',2018,4,'I.G.P.','SEGUNDO',4,'Loja','2772');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
76,sysdate,'system','GC','2018',4,'I.G.P.','SEGUNDO',4,'Orgiva','2793');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
77,sysdate,'system','PN',2018,4,'I.G.S.','SEGUNDO',2,'Gandía','7091');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
78,sysdate,'system','GC','2018',4,'I.G.S.','SEGUNDO',4,'Gandía','7091');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
79,sysdate,'system','PN',2018,5,'I.G.P.','SEGUNDO',2,'Monforte de Lemos','4239');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
80,sysdate,'system','PN','2018',5,'I.G.P.','SEGUNDO',2,'Ribeira','2191');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
81,sysdate,'system','GC',2018,5,'I.G.P.','SEGUNDO',4,'Noia','2175');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
82,sysdate,'system','GC','2018',5,'I.G.P.','SEGUNDO',4,'Carballo','2136');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
83,sysdate,'system','PN',2018,5,'I.G.S.','SEGUNDO',2,'Alcázar de San Juan','1945');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
84,sysdate,'system','PN','2018',5,'I.G.S.','SEGUNDO',2,'Valdepeñas','2031');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
85,sysdate,'system','PN',2018,5,'I.G.S.','SEGUNDO',3,'Cuenca','2283');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
86,sysdate,'system','GC','2018',5,'I.G.S.','SEGUNDO',6,'Cuenca','2283');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
87,sysdate,'system','GC',2018,5,'I.G.S.','SEGUNDO',4,'Tarancón','2391');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
88,sysdate,'system','PN','2018',6,'I.G.P.','SEGUNDO',2,'Santa Cruz de la Palma','5727');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
89,sysdate,'system','GC',2018,6,'I.G.P.','SEGUNDO',4,'Santa Cruz de la Palma','5727');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
90,sysdate,'system','PN','2018',6,'I.G.S.','SEGUNDO',3,'Palencia','5134');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
91,sysdate,'system','GC',2018,6,'I.G.S.','SEGUNDO',6,'Palencia','5134');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
92,sysdate,'system','PN','2018',1,'I.G.P.','TERCERO',2,'Alzira-Algemesí','7003');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
93,sysdate,'system','PN',2018,1,'I.G.P.','TERCERO',2,'Ontiyent','7143');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
94,sysdate,'system','GC','2018',1,'I.G.P.','TERCERO',4,'Paiporta','7145');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
95,sysdate,'system','GC',2018,1,'I.G.P.','TERCERO',4,'Sueca','7199');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
96,sysdate,'system','PN','2018',1,'I.G.S.','TERCERO',3,'Cáceres','1579');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
97,sysdate,'system','GC',2018,1,'I.G.S.','TERCERO',6,'Cáceres','1579');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
98,sysdate,'system','PN','2018',1,'I.G.S.','TERCERO',2,'Mérida','712');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
99,sysdate,'system','GC',2018,1,'I.G.S.','TERCERO',4,'Mérida','712');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
100,sysdate,'system','PN','2018',2,'I.G.P.','TERCERO',2,'Orihuela','235');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
101,sysdate,'system','PN',2018,2,'I.G.P.','TERCERO',2,'Molina de Segura','4582');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
102,sysdate,'system','PN','2018',2,'I.G.P.','TERCERO',2,'Yecla','4599');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
103,sysdate,'system','GC',2018,2,'I.G.P.','TERCERO',4,'Lorca','4579');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
104,sysdate,'system','GC','2018',2,'I.G.P.','TERCERO',4,'Cieza','4574');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
105,sysdate,'system','PN',2018,2,'I.G.S.','TERCERO',3,'Palma de Mallorca','836');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
106,sysdate,'system','PN','2018',2,'I.G.S.','TERCERO',2,'Manacor','827');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
107,sysdate,'system','GC',2018,2,'I.G.S.','TERCERO',6,'Palma de Mallorca','836');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
108,sysdate,'system','GC','2018',2,'I.G.S.','TERCERO',4,'Manacor','827');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
109,sysdate,'system','PN',2018,3,'I.G.P.','TERCERO',2,'San Juan de Analfarache','6143');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
110,sysdate,'system','PN','2018',3,'I.G.P.','TERCERO',2,'Puerto de Santa María y Puerto Real','5727');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
111,sysdate,'system','GC',2018,3,'I.G.P.','TERCERO',4,'Chiclana de la Frontera','1776');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
112,sysdate,'system','GC','2018',3,'I.G.P.','TERCERO',4,'Jerez de la Frontera','1782');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
113,sysdate,'system','GC',2018,3,'I.G.P.','TERCERO',4,'Vejer de la Frontera','1802');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
114,sysdate,'system','PN','2018',3,'I.G.S.','TERCERO',3,'Almería','292');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
115,sysdate,'system','GC',2018,3,'I.G.S.','TERCERO',6,'Almería','292');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
116,sysdate,'system','PN','2018',3,'I.G.S.','TERCERO',7,'Ceuta','8110');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
117,sysdate,'system','GC',2018,3,'I.G.S.','TERCERO',6,'Ceuta','8110');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
118,sysdate,'system','PN','2018',4,'I.G.P.','TERCERO',2,'Almendralejo','640');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
119,sysdate,'system','GC',2018,4,'I.G.P.','TERCERO',4,'Llerena','702');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
120,sysdate,'system','GC','2018',4,'I.G.P.','TERCERO',4,'Zafra','789');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
121,sysdate,'system','GC',2018,4,'I.G.P.','TERCERO',4,'Jerez de los Caballeros','699');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
122,sysdate,'system','GC','2018',4,'I.G.P.','TERCERO',4,'Villanueva de la Serena','784');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
123,sysdate,'system','PN',2018,4,'I.G.S.','TERCERO',3,'Guipuzkoa','3157');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
124,sysdate,'system','PN','2018',4,'I.G.S.','TERCERO',2,'Irún','3157');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
125,sysdate,'system','GC',2018,4,'I.G.S.','TERCERO',6,'Guipuzkoa','3157');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
126,sysdate,'system','GC','2018',4,'I.G.S.','TERCERO',4,'Irún','3157');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
127,sysdate,'system','PN',2018,5,'I.G.P.','TERCERO',2,'Luarca','8112');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
128,sysdate,'system','PN','2018',5,'I.G.P.','TERCERO',2,'Pola de Siero','5028');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
129,sysdate,'system','PN',2018,5,'I.G.P.','TERCERO',2,'Sama de Langreo','4994');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
130,sysdate,'system','GC','2018',5,'I.G.P.','TERCERO',4,'Llanes','4998');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
131,sysdate,'system','GC',2018,5,'I.G.P.','TERCERO',4,'Pravia','5013');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
132,sysdate,'system','GC','2018',5,'I.G.P.','TERCERO',4,'Sama de Langreo','4994');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
133,sysdate,'system','PN',2018,5,'I.G.S.','TERCERO',3,'A Coruña','2148');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
134,sysdate,'system','PN','2018',5,'I.G.S.','TERCERO',2,'Ferrol-Narón','2154');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
135,sysdate,'system','GC',2018,5,'I.G.S.','TERCERO',6,'A Coruña','2148');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
136,sysdate,'system','GC','2018',5,'I.G.S.','TERCERO',4,'El Ferrol','2154');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
137,sysdate,'system','PN',2018,6,'I.G.P.','TERCERO',2,'La Laguna','5723');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
138,sysdate,'system','PN','2018',6,'I.G.P.','TERCERO',2,'Pto de la Cruz Los Realejos','5717');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
139,sysdate,'system','GC',2018,6,'I.G.P.','TERCERO',4,'Costa de Teguise','5256');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
140,sysdate,'system','PN','2018',6,'I.G.P.','TERCERO',2,'Arrecife','5237');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
141,sysdate,'system','PN',2018,6,'I.G.S.','TERCERO',3,'León','3674');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
142,sysdate,'system','PN','2018',6,'I.G.S.','TERCERO',2,'Ponferrada','3699');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
143,sysdate,'system','GC',2018,6,'I.G.S.','TERCERO',6,'León','3674');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
144,sysdate,'system','GC','2018',6,'I.G.S.','TERCERO',4,'Ponferrada','3699');
INSERT INTO INSPECCIONES (ID,FECHA_ALTA,USERNAME_ALTA,AMBITO,ANIO,ID_EQUIPO,TIPO_INSPECCION,CUATRIMESTRE,TIPO_UNIDAD,NOMBRE_UNIDAD,ID_MUNICIPIO) VALUES (
145,sysdate,'system','PN',2018,7,'I.T_CIE','TERCERO',5,'Murcia','4585');
