/**
 * 
 */
package es.mira.progesin.web.beans;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.mock;

import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.ToggleEvent;

import es.mira.progesin.persistence.entities.Inspeccion;
import es.mira.progesin.persistence.entities.SolicitudDocumentacionPrevia;

/**
 * 
 * 
 * @author Ezentis
 */
public class SolicitudDocPreviaBeanTest {
    
    /**
     * @throws java.lang.Exception ex
     */
    @BeforeClass
    public static void setUpBeforeClass() throws Exception {
    }
    
    /**
     * @throws java.lang.Exception ex
     */
    @AfterClass
    public static void tearDownAfterClass() throws Exception {
    }
    
    /**
     * @throws java.lang.Exception ex
     */
    @Before
    public void setUp() throws Exception {
    }
    
    /**
     * @throws java.lang.Exception ex
     */
    @After
    public void tearDown() throws Exception {
    }
    
    /**
     * @throws java.lang.Exception ex
     */
    @Test
    public void type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertThat(SolicitudDocPreviaBean.class, notNullValue());
    }
    
    /**
     * @throws java.lang.Exception ex
     */
    @Test
    public void instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        assertThat(target, notNullValue());
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#crearSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void crearSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.crearSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for
     * {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#getFormModificarSolicitud(SolicitudDocumentacionPrevia)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void getFormModificarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        SolicitudDocumentacionPrevia solicitud = mock(SolicitudDocumentacionPrevia.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        String actual = target.getFormModificarSolicitud(solicitud);
        // then
        // e.g. : verify(mocked).called();
        String expected = null;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for
     * {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#visualizarSolicitud(SolicitudDocumentacionPrevia)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void visualizarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        SolicitudDocumentacionPrevia solicitud = mock(SolicitudDocumentacionPrevia.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        String actual = target.visualizarSolicitud(solicitud);
        // then
        // e.g. : verify(mocked).called();
        String expected = null;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#validacionApoyo()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void validacionApoyo() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.validacionApoyo();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#validacionJefeEquipo()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void validacionJefeEquipo() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.validacionJefeEquipo();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#getFormularioCrearSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void getFormularioCrearSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.getFormularioCrearSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#init()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void init() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.init();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#descargarFichero(Long)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void descargarFichero() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        Long idDocumento = null;
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.descargarFichero(idDocumento);
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#onFlowProcess(FlowEvent)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void onFlowProcess() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        FlowEvent event = mock(FlowEvent.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        String actual = target.onFlowProcess(event);
        // then
        // e.g. : verify(mocked).called();
        String expected = null;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#onToggle(ToggleEvent)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void onToggle() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        ToggleEvent e = mock(ToggleEvent.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.onToggle(e);
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for
     * {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#eliminarSolicitud(SolicitudDocumentacionPrevia)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void eliminarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        SolicitudDocumentacionPrevia solicitud = mock(SolicitudDocumentacionPrevia.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.eliminarSolicitud(solicitud);
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#modificarSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void modificarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.modificarSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#enviarSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void enviarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.enviarSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#finalizarSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void finalizarSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.finalizarSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#noConformeSolicitud(String)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void noConformeSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        String motivosNoConforme = null;
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.noConformeSolicitud(motivosNoConforme);
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#getFormBusquedaSolicitudes()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void getFormBusquedaSolicitudes() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.getFormBusquedaSolicitudes();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#limpiarBusqueda()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void limpiarBusqueda() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.limpiarBusqueda();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#buscarSolicitudDocPrevia()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void buscarSolicitudDocPrevia() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.buscarSolicitudDocPrevia();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#autocompletarInspeccion(String)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void autocompletarInspeccion() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        String infoInspeccion = null;
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        List<Inspeccion> actual = target.autocompletarInspeccion(infoInspeccion);
        // then
        // e.g. : verify(mocked).called();
        List<Inspeccion> expected = null;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#imprimirPdf()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void imprimirPdf() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.imprimirPdf();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#inspeccionSinTareasPendientes()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void inspeccionSinTareasPendientes() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        boolean actual = target.inspeccionSinTareasPendientes();
        // then
        // e.g. : verify(mocked).called();
        boolean expected = false;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#usuarioSinTareasPendientes()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void usuarioSinTareasPendientes() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        boolean actual = target.usuarioSinTareasPendientes();
        // then
        // e.g. : verify(mocked).called();
        boolean expected = false;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#nextSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void nextSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.nextSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#previousSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void previousSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        target.previousSolicitud();
        // then
        // e.g. : verify(mocked).called();
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#getCountPagesSolicitud(long)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void getCountPagesSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        long countRegistros = 0L;
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        long actual = target.getCountPagesSolicitud(countRegistros);
        // then
        // e.g. : verify(mocked).called();
        long expected = 0L;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#getCountRegistrosSolicitud()}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void getCountRegistrosSolicitud() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        long actual = target.getCountRegistrosSolicitud();
        // then
        // e.g. : verify(mocked).called();
        long expected = 0L;
        assertThat(actual, is(equalTo(expected)));
    }
    
    /**
     * Test method for
     * {@link es.mira.progesin.web.beans.SolicitudDocPreviaBean#copiaSolicitudDocPreviaBusqueda(SolicitudDocPreviaBusqueda)}.
     * @throws java.lang.Exception ex
     */
    @Test
    public void copiaSolicitudDocPreviaBusqueda() throws Exception {
        // TODO auto-generated by JUnit Helper.
        SolicitudDocPreviaBean target = new SolicitudDocPreviaBean();
        // given
        SolicitudDocPreviaBusqueda solicitudBusqueda = mock(SolicitudDocPreviaBusqueda.class);
        // e.g. : given(mocked.called()).willReturn(1);
        // when
        SolicitudDocPreviaBusqueda actual = target.copiaSolicitudDocPreviaBusqueda(solicitudBusqueda);
        // then
        // e.g. : verify(mocked).called();
        SolicitudDocPreviaBusqueda expected = null;
        assertThat(actual, is(equalTo(expected)));
    }
    
}
